export const acmActions = [
  "AddTagsToCertificate",
  "CreateAcmeDomainValidation",
  "CreateAcmeEndpoint",
  "CreateAcmeExternalAccountBinding",
  "DeleteAcmeDomainValidation",
  "DeleteAcmeEndpoint",
  "DeleteAcmeExternalAccountBinding",
  "DeleteCertificate",
  "DescribeAcmeAccount",
  "DescribeAcmeDomainValidation",
  "DescribeAcmeEndpoint",
  "DescribeAcmeExternalAccountBinding",
  "DescribeCertificate",
  "ExportCertificate",
  "GetAccountConfiguration",
  "GetAcmeExternalAccountBindingCredentials",
  "GetCertificate",
  "ImportCertificate",
  "ListAcmeAccounts",
  "ListAcmeDomainValidations",
  "ListAcmeEndpoints",
  "ListAcmeExternalAccountBindings",
  "ListCertificates",
  "ListTagsForCertificate",
  "ListTagsForResource",
  "PutAccountConfiguration",
  "RemoveTagsFromCertificate",
  "RenewCertificate",
  "RequestCertificate",
  "ResendValidationEmail",
  "RevokeAcmeAccount",
  "RevokeAcmeExternalAccountBinding",
  "RevokeCertificate",
  "SearchCertificates",
  "TagResource",
  "UntagResource",
  "UpdateAcmeDomainValidation",
  "UpdateAcmeEndpoint",
  "UpdateCertificate",
  "UpdateCertificateOptions",
] as const;

export type AcmAction = (typeof acmActions)[number];

export function acm(action: AcmAction | "*"): `acm:${AcmAction | "*"}` {
  return `acm:${action}` as `acm:${AcmAction | "*"}`;
}
