export const aidevopsActions = [
  "AllowVendedLogDeliveryForResource",
  "AssociateService",
  "CreateAgentSpace",
  "CreateBacklogTask",
  "CreateChat",
  "CreateKnowledgeItem",
  "CreateOneTimeLoginSession",
  "CreatePrivateConnection",
  "DeleteAgentSpace",
  "DeleteKnowledgeItem",
  "DeletePrivateConnection",
  "DeregisterService",
  "DescribePrivateConnection",
  "DescribeServices",
  "DescribeSupportLevel",
  "DisableOperatorApp",
  "DisassociateService",
  "DiscoverTopology",
  "EnableOperatorApp",
  "EndChatForCase",
  "GetAccountUsage",
  "GetAgentSpace",
  "GetAssociation",
  "GetBacklogTask",
  "GetKnowledgeItem",
  "GetOperatorApp",
  "GetRecommendation",
  "GetService",
  "InitiateChatForCase",
  "ListAgentSpaces",
  "ListAssociations",
  "ListBacklogTasks",
  "ListChats",
  "ListExecutions",
  "ListGoals",
  "ListJournalRecords",
  "ListKnowledgeItems",
  "ListKnowledgeItemVersions",
  "ListPendingMessages",
  "ListPrivateConnections",
  "ListRecommendations",
  "ListServices",
  "ListTagsForResource",
  "ListWebhooks",
  "RegisterService",
  "SearchServiceAccessibleResource",
  "SendMessage",
  "TagResource",
  "UntagResource",
  "UpdateAgentSpace",
  "UpdateAssociation",
  "UpdateBacklogTask",
  "UpdateGoal",
  "UpdateKnowledgeItem",
  "UpdateOperatorAppIdpConfig",
  "UpdatePrivateConnectionCertificate",
  "UpdateRecommendation",
  "ValidateAwsAssociations",
] as const;

export type AidevopsAction = (typeof aidevopsActions)[number];

export function aidevops(action: AidevopsAction | "*"): `aidevops:${AidevopsAction | "*"}` {
  return `aidevops:${action}` as `aidevops:${AidevopsAction | "*"}`;
}
