export const amplifyActions = [
  "AssociateWebACL",
  "CreateApp",
  "CreateBackendEnvironment",
  "CreateBranch",
  "CreateDeployment",
  "CreateDomainAssociation",
  "CreateWebHook",
  "DeleteApp",
  "DeleteBackendEnvironment",
  "DeleteBranch",
  "DeleteDomainAssociation",
  "DeleteJob",
  "DeleteWebHook",
  "DisassociateWebACL",
  "GenerateAccessLogs",
  "GetApp",
  "GetArtifactUrl",
  "GetBackendEnvironment",
  "GetBranch",
  "GetDomainAssociation",
  "GetJob",
  "GetWebACLForResource",
  "GetWebHook",
  "ListApps",
  "ListArtifacts",
  "ListBackendEnvironments",
  "ListBranches",
  "ListDomainAssociations",
  "ListJobs",
  "ListResourcesForWebACL",
  "ListTagsForResource",
  "ListWebHooks",
  "StartDeployment",
  "StartJob",
  "StopJob",
  "TagResource",
  "UntagResource",
  "UpdateApp",
  "UpdateBranch",
  "UpdateDomainAssociation",
  "UpdateWebHook",
] as const;

export type AmplifyAction = (typeof amplifyActions)[number];

export function amplify(action: AmplifyAction | "*"): `amplify:${AmplifyAction | "*"}` {
  return `amplify:${action}` as `amplify:${AmplifyAction | "*"}`;
}
