export const aossActions = [
  "AddCollectionToCollectionGroup",
  "APIAccessAll",
  "BatchGetCollection",
  "BatchGetCollectionGroup",
  "BatchGetEffectiveLifecyclePolicy",
  "BatchGetLifecyclePolicy",
  "BatchGetVpcEndpoint",
  "CreateAccessPolicy",
  "CreateCollection",
  "CreateCollectionGroup",
  "CreateIndex",
  "CreateLifecyclePolicy",
  "CreateSecurityConfig",
  "CreateSecurityPolicy",
  "CreateVpcEndpoint",
  "DashboardsAccessAll",
  "DeleteAccessPolicy",
  "DeleteCollection",
  "DeleteCollectionGroup",
  "DeleteIndex",
  "DeleteLifecyclePolicy",
  "DeleteSecurityConfig",
  "DeleteSecurityPolicy",
  "DeleteVpcEndpoint",
  "GetAccessPolicy",
  "GetAccountSettings",
  "GetIndex",
  "GetPoliciesStats",
  "GetSecurityConfig",
  "GetSecurityPolicy",
  "ListAccessPolicies",
  "ListCollectionGroups",
  "ListCollections",
  "ListLifecyclePolicies",
  "ListSecurityConfigs",
  "ListSecurityPolicies",
  "ListTagsForResource",
  "ListVpcEndpoints",
  "TagResource",
  "UntagResource",
  "UpdateAccessPolicy",
  "UpdateAccountSettings",
  "UpdateCollection",
  "UpdateCollectionGroup",
  "UpdateIndex",
  "UpdateLifecyclePolicy",
  "UpdateSecurityConfig",
  "UpdateSecurityPolicy",
  "UpdateVpcEndpoint",
] as const;

export type AossAction = (typeof aossActions)[number];

export function aoss(action: AossAction | "*"): `aoss:${AossAction | "*"}` {
  return `aoss:${action}` as `aoss:${AossAction | "*"}`;
}
