export const appconfigActions = [
  "CreateApplication",
  "CreateConfigurationProfile",
  "CreateDeploymentStrategy",
  "CreateEnvironment",
  "CreateExtension",
  "CreateExtensionAssociation",
  "CreateHostedConfigurationVersion",
  "DeleteApplication",
  "DeleteConfigurationProfile",
  "DeleteDeploymentStrategy",
  "DeleteEnvironment",
  "DeleteExtension",
  "DeleteExtensionAssociation",
  "DeleteHostedConfigurationVersion",
  "GetAccountSettings",
  "GetApplication",
  "GetConfiguration",
  "GetConfigurationProfile",
  "GetDeployment",
  "GetDeploymentStrategy",
  "GetEnvironment",
  "GetExtension",
  "GetExtensionAssociation",
  "GetHostedConfigurationVersion",
  "GetLatestConfiguration",
  "ListApplications",
  "ListConfigurationProfiles",
  "ListDeployments",
  "ListDeploymentStrategies",
  "ListEnvironments",
  "ListExtensionAssociations",
  "ListExtensions",
  "ListHostedConfigurationVersions",
  "ListTagsForResource",
  "StartConfigurationSession",
  "StartDeployment",
  "StopDeployment",
  "TagResource",
  "UntagResource",
  "UpdateAccountSettings",
  "UpdateApplication",
  "UpdateConfigurationProfile",
  "UpdateDeploymentStrategy",
  "UpdateEnvironment",
  "UpdateExtension",
  "UpdateExtensionAssociation",
  "ValidateConfiguration",
] as const;

export type AppconfigAction = (typeof appconfigActions)[number];

export function appconfig(action: AppconfigAction | "*"): `appconfig:${AppconfigAction | "*"}` {
  return `appconfig:${action}` as `appconfig:${AppconfigAction | "*"}`;
}
