export const appmeshActions = [
  "CreateGatewayRoute",
  "CreateMesh",
  "CreateRoute",
  "CreateVirtualGateway",
  "CreateVirtualNode",
  "CreateVirtualRouter",
  "CreateVirtualService",
  "DeleteGatewayRoute",
  "DeleteMesh",
  "DeleteMeshPolicy",
  "DeleteRoute",
  "DeleteVirtualGateway",
  "DeleteVirtualNode",
  "DeleteVirtualRouter",
  "DeleteVirtualService",
  "DescribeGatewayRoute",
  "DescribeMesh",
  "DescribeRoute",
  "DescribeVirtualGateway",
  "DescribeVirtualNode",
  "DescribeVirtualRouter",
  "DescribeVirtualService",
  "GetMeshPolicy",
  "ListGatewayRoutes",
  "ListMeshes",
  "ListRoutes",
  "ListTagsForResource",
  "ListVirtualGateways",
  "ListVirtualNodes",
  "ListVirtualRouters",
  "ListVirtualServices",
  "PutMeshPolicy",
  "StreamAggregatedResources",
  "TagResource",
  "UntagResource",
  "UpdateGatewayRoute",
  "UpdateMesh",
  "UpdateRoute",
  "UpdateVirtualGateway",
  "UpdateVirtualNode",
  "UpdateVirtualRouter",
  "UpdateVirtualService",
] as const;

export type AppmeshAction = (typeof appmeshActions)[number];

export function appmesh(action: AppmeshAction | "*"): `appmesh:${AppmeshAction | "*"}` {
  return `appmesh:${action}` as `appmesh:${AppmeshAction | "*"}`;
}
