export const apprunnerActions = [
  "AssociateCustomDomain",
  "AssociateWebAcl",
  "CreateAutoScalingConfiguration",
  "CreateConnection",
  "CreateObservabilityConfiguration",
  "CreateService",
  "CreateVpcConnector",
  "CreateVpcIngressConnection",
  "DeleteAutoScalingConfiguration",
  "DeleteConnection",
  "DeleteObservabilityConfiguration",
  "DeleteService",
  "DeleteVpcConnector",
  "DeleteVpcIngressConnection",
  "DescribeAutoScalingConfiguration",
  "DescribeCustomDomains",
  "DescribeObservabilityConfiguration",
  "DescribeOperation",
  "DescribeService",
  "DescribeVpcConnector",
  "DescribeVpcIngressConnection",
  "DescribeWebAclForService",
  "DisassociateCustomDomain",
  "DisassociateWebAcl",
  "ListAssociatedServicesForWebAcl",
  "ListAutoScalingConfigurations",
  "ListConnections",
  "ListObservabilityConfigurations",
  "ListOperations",
  "ListServices",
  "ListServicesForAutoScalingConfiguration",
  "ListTagsForResource",
  "ListVpcConnectors",
  "ListVpcIngressConnections",
  "PauseService",
  "ResumeService",
  "StartDeployment",
  "TagResource",
  "UntagResource",
  "UpdateDefaultAutoScalingConfiguration",
  "UpdateService",
  "UpdateVpcIngressConnection",
] as const;

export type ApprunnerAction = (typeof apprunnerActions)[number];

export function apprunner(action: ApprunnerAction | "*"): `apprunner:${ApprunnerAction | "*"}` {
  return `apprunner:${action}` as `apprunner:${ApprunnerAction | "*"}`;
}
