export const apsActions = [
  "CreateAlertManagerAlerts",
  "CreateAlertManagerDefinition",
  "CreateAnomalyDetector",
  "CreateLoggingConfiguration",
  "CreateQueryLoggingConfiguration",
  "CreateRuleGroupsNamespace",
  "CreateScraper",
  "CreateWorkspace",
  "DeleteAlertManagerDefinition",
  "DeleteAlertManagerSilence",
  "DeleteAnomalyDetector",
  "DeleteLoggingConfiguration",
  "DeleteQueryLoggingConfiguration",
  "DeleteResourcePolicy",
  "DeleteRuleGroupsNamespace",
  "DeleteScraper",
  "DeleteScraperLoggingConfiguration",
  "DeleteWorkspace",
  "DescribeAlertManagerDefinition",
  "DescribeAnomalyDetector",
  "DescribeLoggingConfiguration",
  "DescribeQueryLoggingConfiguration",
  "DescribeResourcePolicy",
  "DescribeRuleGroupsNamespace",
  "DescribeScraper",
  "DescribeScraperLoggingConfiguration",
  "DescribeWorkspace",
  "DescribeWorkspaceConfiguration",
  "GetAlertManagerSilence",
  "GetAlertManagerStatus",
  "GetDefaultScraperConfiguration",
  "GetLabels",
  "GetMetricMetadata",
  "GetSeries",
  "ListAlertManagerAlertGroups",
  "ListAlertManagerAlerts",
  "ListAlertManagerReceivers",
  "ListAlertManagerSilences",
  "ListAlerts",
  "ListAnomalyDetectors",
  "ListRuleGroupsNamespaces",
  "ListRules",
  "ListScrapers",
  "ListTagsForResource",
  "ListWorkspaces",
  "PreviewAnomalyDetector",
  "PutAlertManagerDefinition",
  "PutAlertManagerSilences",
  "PutAnomalyDetector",
  "PutResourcePolicy",
  "PutRuleGroupsNamespace",
  "QueryMetrics",
  "RemoteWrite",
  "TagResource",
  "UntagResource",
  "UpdateLoggingConfiguration",
  "UpdateQueryLoggingConfiguration",
  "UpdateScraper",
  "UpdateScraperLoggingConfiguration",
  "UpdateWorkspaceAlias",
  "UpdateWorkspaceConfiguration",
] as const;

export type ApsAction = (typeof apsActions)[number];

export function aps(action: ApsAction | "*"): `aps:${ApsAction | "*"}` {
  return `aps:${action}` as `aps:${ApsAction | "*"}`;
}
