export const auditmanagerActions = [
  "AssociateAssessmentReportEvidenceFolder",
  "BatchAssociateAssessmentReportEvidence",
  "BatchCreateDelegationByAssessment",
  "BatchDeleteDelegationByAssessment",
  "BatchDisassociateAssessmentReportEvidence",
  "BatchImportEvidenceToAssessmentControl",
  "CreateAssessment",
  "CreateAssessmentFramework",
  "CreateAssessmentReport",
  "CreateControl",
  "DeleteAssessment",
  "DeleteAssessmentFramework",
  "DeleteAssessmentFrameworkShare",
  "DeleteAssessmentReport",
  "DeleteControl",
  "DeregisterAccount",
  "DeregisterOrganizationAdminAccount",
  "DisassociateAssessmentReportEvidenceFolder",
  "GetAccountStatus",
  "GetAssessment",
  "GetAssessmentFramework",
  "GetAssessmentReportUrl",
  "GetChangeLogs",
  "GetControl",
  "GetDelegations",
  "GetEvidence",
  "GetEvidenceByEvidenceFolder",
  "GetEvidenceFileUploadUrl",
  "GetEvidenceFolder",
  "GetEvidenceFoldersByAssessment",
  "GetEvidenceFoldersByAssessmentControl",
  "GetInsights",
  "GetInsightsByAssessment",
  "GetOrganizationAdminAccount",
  "GetServicesInScope",
  "GetSettings",
  "ListAssessmentControlInsightsByControlDomain",
  "ListAssessmentFrameworks",
  "ListAssessmentFrameworkShareRequests",
  "ListAssessmentReports",
  "ListAssessments",
  "ListControlDomainInsights",
  "ListControlDomainInsightsByAssessment",
  "ListControlInsightsByControlDomain",
  "ListControls",
  "ListKeywordsForDataSource",
  "ListNotifications",
  "ListTagsForResource",
  "RegisterAccount",
  "RegisterOrganizationAdminAccount",
  "StartAssessmentFrameworkShare",
  "TagResource",
  "UntagResource",
  "UpdateAssessment",
  "UpdateAssessmentControl",
  "UpdateAssessmentControlSetStatus",
  "UpdateAssessmentFramework",
  "UpdateAssessmentFrameworkShare",
  "UpdateAssessmentStatus",
  "UpdateControl",
  "UpdateSettings",
  "ValidateAssessmentReportIntegrity",
] as const;

export type AuditmanagerAction = (typeof auditmanagerActions)[number];

export function auditmanager(action: AuditmanagerAction | "*"): `auditmanager:${AuditmanagerAction | "*"}` {
  return `auditmanager:${action}` as `auditmanager:${AuditmanagerAction | "*"}`;
}
