export const autoscalingActions = [
  "AttachInstances",
  "AttachLoadBalancers",
  "AttachLoadBalancerTargetGroups",
  "AttachTrafficSources",
  "BatchDeleteScheduledAction",
  "BatchPutScheduledUpdateGroupAction",
  "CancelInstanceRefresh",
  "CompleteLifecycleAction",
  "CreateAutoScalingGroup",
  "CreateLaunchConfiguration",
  "CreateOrUpdateTags",
  "DeleteAutoScalingGroup",
  "DeleteLaunchConfiguration",
  "DeleteLifecycleHook",
  "DeleteNotificationConfiguration",
  "DeletePolicy",
  "DeleteScheduledAction",
  "DeleteTags",
  "DeleteWarmPool",
  "DescribeAccountLimits",
  "DescribeAccountSettings",
  "DescribeAdjustmentTypes",
  "DescribeAutoScalingGroups",
  "DescribeAutoScalingInstances",
  "DescribeAutoScalingNotificationTypes",
  "DescribeInstanceRefreshes",
  "DescribeLaunchConfigurations",
  "DescribeLifecycleHooks",
  "DescribeLifecycleHookTypes",
  "DescribeLoadBalancers",
  "DescribeLoadBalancerTargetGroups",
  "DescribeMetricCollectionTypes",
  "DescribeNotificationConfigurations",
  "DescribePolicies",
  "DescribeScalingActivities",
  "DescribeScalingProcessTypes",
  "DescribeScheduledActions",
  "DescribeTags",
  "DescribeTerminationPolicyTypes",
  "DescribeTrafficSources",
  "DescribeWarmPool",
  "DetachInstances",
  "DetachLoadBalancers",
  "DetachLoadBalancerTargetGroups",
  "DetachTrafficSources",
  "DisableMetricsCollection",
  "EnableMetricsCollection",
  "EnterStandby",
  "ExecutePolicy",
  "ExitStandby",
  "GetPredictiveScalingForecast",
  "LaunchInstances",
  "PutAccountSetting",
  "PutLifecycleHook",
  "PutNotificationConfiguration",
  "PutScalingPolicy",
  "PutScheduledUpdateGroupAction",
  "PutWarmPool",
  "RecordLifecycleActionHeartbeat",
  "ResumeProcesses",
  "RollbackInstanceRefresh",
  "SetDesiredCapacity",
  "SetInstanceHealth",
  "SetInstanceProtection",
  "StartInstanceRefresh",
  "SuspendProcesses",
  "TerminateInstanceInAutoScalingGroup",
  "UpdateAutoScalingGroup",
] as const;

export type AutoscalingAction = (typeof autoscalingActions)[number];

export function autoscaling(action: AutoscalingAction | "*"): `autoscaling:${AutoscalingAction | "*"}` {
  return `autoscaling:${action}` as `autoscaling:${AutoscalingAction | "*"}`;
}
