export const awsExternalAnthropicActions = [
  "ArchiveAgent",
  "ArchiveEnvironment",
  "ArchiveMemoryStore",
  "ArchiveSession",
  "ArchiveVault",
  "ArchiveWorkspace",
  "AssumeConsole",
  "CallWithBearerToken",
  "CancelBatchInference",
  "CountTokens",
  "CreateAgent",
  "CreateBatchInference",
  "CreateEnvironment",
  "CreateFile",
  "CreateInference",
  "CreateMemoryStore",
  "CreateSession",
  "CreateSkill",
  "CreateUserProfile",
  "CreateUserProfileEnrollmentUrl",
  "CreateVault",
  "CreateWorkspace",
  "DeleteBatchInference",
  "DeleteEnvironment",
  "DeleteFile",
  "DeleteMemoryStore",
  "DeleteSession",
  "DeleteSkill",
  "DeleteVault",
  "GetAccountStatus",
  "GetAgent",
  "GetBatchInference",
  "GetEnvironment",
  "GetFile",
  "GetMemoryStore",
  "GetModel",
  "GetSession",
  "GetSkill",
  "GetUserProfile",
  "GetVault",
  "GetWorkspace",
  "ListAgents",
  "ListBatchInferences",
  "ListEnvironments",
  "ListFiles",
  "ListMemoryStores",
  "ListModels",
  "ListSessions",
  "ListSkills",
  "ListTagsForResource",
  "ListUserProfiles",
  "ListVaults",
  "ListWorkspaces",
  "TagResource",
  "UntagResource",
  "UpdateAgent",
  "UpdateEnvironment",
  "UpdateMemoryStore",
  "UpdateSession",
  "UpdateSkill",
  "UpdateUserProfile",
  "UpdateVault",
  "UpdateWorkspace",
] as const;

export type AwsExternalAnthropicAction = (typeof awsExternalAnthropicActions)[number];

export function awsExternalAnthropic(action: AwsExternalAnthropicAction | "*"): `aws-external-anthropic:${AwsExternalAnthropicAction | "*"}` {
  return `aws-external-anthropic:${action}` as `aws-external-anthropic:${AwsExternalAnthropicAction | "*"}`;
}
