export const batchActions = [
  "CancelJob",
  "CreateComputeEnvironment",
  "CreateConsumableResource",
  "CreateJobQueue",
  "CreateQuotaShare",
  "CreateSchedulingPolicy",
  "CreateServiceEnvironment",
  "DeleteComputeEnvironment",
  "DeleteConsumableResource",
  "DeleteJobQueue",
  "DeleteQuotaShare",
  "DeleteSchedulingPolicy",
  "DeleteServiceEnvironment",
  "DeregisterJobDefinition",
  "DescribeComputeEnvironments",
  "DescribeConsumableResource",
  "DescribeJobDefinitions",
  "DescribeJobQueues",
  "DescribeJobs",
  "DescribeQuotaShare",
  "DescribeSchedulingPolicies",
  "DescribeServiceEnvironments",
  "DescribeServiceJob",
  "GetJobQueueSnapshot",
  "ListConsumableResources",
  "ListJobs",
  "ListJobsByConsumableResource",
  "ListQuotaShares",
  "ListSchedulingPolicies",
  "ListServiceJobs",
  "ListTagsForResource",
  "RegisterJobDefinition",
  "SubmitJob",
  "SubmitServiceJob",
  "TagResource",
  "TerminateJob",
  "TerminateServiceJob",
  "UntagResource",
  "UpdateComputeEnvironment",
  "UpdateConsumableResource",
  "UpdateJobQueue",
  "UpdateQuotaShare",
  "UpdateSchedulingPolicy",
  "UpdateServiceEnvironment",
  "UpdateServiceJob",
] as const;

export type BatchAction = (typeof batchActions)[number];

export function batch(action: BatchAction | "*"): `batch:${BatchAction | "*"}` {
  return `batch:${action}` as `batch:${BatchAction | "*"}`;
}
