export const bedrockMantleActions = [
  "ArchiveProject",
  "AssociateCustomizedModel",
  "CallWithBearerToken",
  "CancelFineTuningJob",
  "CancelInference",
  "CountTokens",
  "CreateCustomizedModel",
  "CreateFile",
  "CreateFineTuningJob",
  "CreateInference",
  "CreateProject",
  "CreateReservation",
  "DeleteCustomizedModel",
  "DeleteFile",
  "DeleteInference",
  "DeleteReservation",
  "DisassociateCustomizedModel",
  "GetAccountDataRetention",
  "GetCustomizedModel",
  "GetFile",
  "GetFineTuningJob",
  "GetInference",
  "GetModel",
  "GetProject",
  "GetReservation",
  "ListCustomizedModelAssociations",
  "ListCustomizedModels",
  "ListFiles",
  "ListFineTuningJobs",
  "ListModels",
  "ListProjects",
  "ListReservations",
  "ListTagsForResource",
  "PutAccountDataRetention",
  "TagResource",
  "UntagResource",
  "UpdateProject",
  "UpdateReservation",
] as const;

export type BedrockMantleAction = (typeof bedrockMantleActions)[number];

export function bedrockMantle(action: BedrockMantleAction | "*"): `bedrock-mantle:${BedrockMantleAction | "*"}` {
  return `bedrock-mantle:${action}` as `bedrock-mantle:${BedrockMantleAction | "*"}`;
}
