export const casesActions = [
  "BatchGetCaseRule",
  "BatchGetField",
  "BatchPutFieldOptions",
  "CreateCase",
  "CreateCaseRule",
  "CreateDomain",
  "CreateField",
  "CreateLayout",
  "CreateRelatedItem",
  "CreateTemplate",
  "DeleteCase",
  "DeleteCaseRule",
  "DeleteDomain",
  "DeleteField",
  "DeleteLayout",
  "DeleteRelatedItem",
  "DeleteTemplate",
  "GetCase",
  "GetCaseAuditEvents",
  "GetCaseEventConfiguration",
  "GetDomain",
  "GetLayout",
  "GetTemplate",
  "ListCaseRules",
  "ListCasesForContact",
  "ListDomains",
  "ListFieldOptions",
  "ListFields",
  "ListLayouts",
  "ListTagsForResource",
  "ListTemplates",
  "PutCaseEventConfiguration",
  "SearchAllRelatedItems",
  "SearchCases",
  "SearchRelatedItems",
  "TagResource",
  "UntagResource",
  "UpdateCase",
  "UpdateCaseRule",
  "UpdateField",
  "UpdateLayout",
  "UpdateRelatedItem",
  "UpdateTemplate",
] as const;

export type CasesAction = (typeof casesActions)[number];

export function cases(action: CasesAction | "*"): `cases:${CasesAction | "*"}` {
  return `cases:${action}` as `cases:${CasesAction | "*"}`;
}
