export const ceActions = [
  "CreateAnomalyMonitor",
  "CreateAnomalySubscription",
  "CreateCostCategoryDefinition",
  "CreateNotificationSubscription",
  "CreateReport",
  "DeleteAnomalyMonitor",
  "DeleteAnomalySubscription",
  "DeleteCostCategoryDefinition",
  "DeleteNotificationSubscription",
  "DeleteReport",
  "DescribeCostCategoryDefinition",
  "DescribeNotificationSubscription",
  "DescribeReport",
  "GetAnomalies",
  "GetAnomalyMonitors",
  "GetAnomalySubscriptions",
  "GetApproximateUsageRecords",
  "GetCommitmentPurchaseAnalysis",
  "GetConsoleActionSetEnforced",
  "GetCostAndUsage",
  "GetCostAndUsageComparisons",
  "GetCostAndUsageWithResources",
  "GetCostCategories",
  "GetCostComparisonDrivers",
  "GetCostForecast",
  "GetDimensionValues",
  "GetPreferences",
  "GetReservationCoverage",
  "GetReservationPurchaseRecommendation",
  "GetReservationUtilization",
  "GetRightsizingRecommendation",
  "GetSavingsPlanPurchaseRecommendationDetails",
  "GetSavingsPlansCoverage",
  "GetSavingsPlansPurchaseRecommendation",
  "GetSavingsPlansUtilization",
  "GetSavingsPlansUtilizationDetails",
  "GetTags",
  "GetUsageForecast",
  "ListCommitmentPurchaseAnalyses",
  "ListCostAllocationTagBackfillHistory",
  "ListCostAllocationTags",
  "ListCostCategoryDefinitions",
  "ListCostCategoryResourceAssociations",
  "ListSavingsPlansPurchaseRecommendationGeneration",
  "ListTagsForResource",
  "ProvideAnomalyFeedback",
  "StartCommitmentPurchaseAnalysis",
  "StartCostAllocationTagBackfill",
  "StartSavingsPlansPurchaseRecommendationGeneration",
  "TagResource",
  "UntagResource",
  "UpdateAnomalyMonitor",
  "UpdateAnomalySubscription",
  "UpdateConsoleActionSetEnforced",
  "UpdateCostAllocationTagsStatus",
  "UpdateCostCategoryDefinition",
  "UpdateNotificationSubscription",
  "UpdatePreferences",
  "UpdateReport",
] as const;

export type CeAction = (typeof ceActions)[number];

export function ce(action: CeAction | "*"): `ce:${CeAction | "*"}` {
  return `ce:${action}` as `ce:${CeAction | "*"}`;
}
