export const cleanroomsMlActions = [
  "CancelTrainedModel",
  "CancelTrainedModelInferenceJob",
  "CreateAudienceModel",
  "CreateConfiguredAudienceModel",
  "CreateConfiguredModelAlgorithm",
  "CreateConfiguredModelAlgorithmAssociation",
  "CreateMLInputChannel",
  "CreateTrainedModel",
  "CreateTrainingDataset",
  "DeleteAudienceGenerationJob",
  "DeleteAudienceModel",
  "DeleteConfiguredAudienceModel",
  "DeleteConfiguredAudienceModelPolicy",
  "DeleteConfiguredModelAlgorithm",
  "DeleteConfiguredModelAlgorithmAssociation",
  "DeleteMLConfiguration",
  "DeleteMLInputChannelData",
  "DeleteTrainedModelOutput",
  "DeleteTrainingDataset",
  "GetAudienceGenerationJob",
  "GetAudienceModel",
  "GetCollaborationConfiguredModelAlgorithmAssociation",
  "GetCollaborationMLInputChannel",
  "GetCollaborationTrainedModel",
  "GetConfiguredAudienceModel",
  "GetConfiguredAudienceModelPolicy",
  "GetConfiguredModelAlgorithm",
  "GetConfiguredModelAlgorithmAssociation",
  "GetMLConfiguration",
  "GetMLInputChannel",
  "GetTrainedModel",
  "GetTrainedModelInferenceJob",
  "GetTrainingDataset",
  "ListAudienceExportJobs",
  "ListAudienceGenerationJobs",
  "ListAudienceModels",
  "ListCollaborationConfiguredModelAlgorithmAssociations",
  "ListCollaborationMLInputChannels",
  "ListCollaborationTrainedModelExportJobs",
  "ListCollaborationTrainedModelInferenceJobs",
  "ListCollaborationTrainedModels",
  "ListConfiguredAudienceModels",
  "ListConfiguredModelAlgorithmAssociations",
  "ListConfiguredModelAlgorithms",
  "ListMLInputChannels",
  "ListTagsForResource",
  "ListTrainedModelInferenceJobs",
  "ListTrainedModels",
  "ListTrainedModelVersions",
  "ListTrainingDatasets",
  "PutConfiguredAudienceModelPolicy",
  "PutMLConfiguration",
  "StartAudienceExportJob",
  "StartAudienceGenerationJob",
  "StartTrainedModelExportJob",
  "StartTrainedModelInferenceJob",
  "TagResource",
  "UnTagResource",
  "UpdateConfiguredAudienceModel",
] as const;

export type CleanroomsMlAction = (typeof cleanroomsMlActions)[number];

export function cleanroomsMl(action: CleanroomsMlAction | "*"): `cleanrooms-ml:${CleanroomsMlAction | "*"}` {
  return `cleanrooms-ml:${action}` as `cleanrooms-ml:${CleanroomsMlAction | "*"}`;
}
