export const cloudwatchActions = [
  "BatchGetServiceLevelIndicatorReport",
  "BatchGetServiceLevelObjectiveBudgetReport",
  "CallWithBearerToken",
  "CreateServiceLevelObjective",
  "DeleteAlarmMuteRule",
  "DeleteAlarms",
  "DeleteAnomalyDetector",
  "DeleteDashboards",
  "DeleteInsightRules",
  "DeleteMetricStream",
  "DeleteServiceLevelObjective",
  "DescribeAlarmHistory",
  "DescribeAlarms",
  "DescribeAlarmsForMetric",
  "DescribeAnomalyDetectors",
  "DescribeInsightRules",
  "DisableAlarmActions",
  "DisableInsightRules",
  "EnableAlarmActions",
  "EnableInsightRules",
  "EnableTopologyDiscovery",
  "GenerateQuery",
  "GenerateQueryResultsSummary",
  "GetAlarmMuteRule",
  "GetDashboard",
  "GetDataset",
  "GetInsightRuleReport",
  "GetMetricData",
  "GetMetricStatistics",
  "GetMetricStream",
  "GetMetricWidgetImage",
  "GetOTelEnrichment",
  "GetService",
  "GetServiceData",
  "GetServiceLevelObjective",
  "GetTopologyDiscoveryStatus",
  "GetTopologyMap",
  "Link",
  "ListAlarmMuteRules",
  "ListDashboards",
  "ListEntitiesForMetric",
  "ListManagedInsightRules",
  "ListMetrics",
  "ListMetricStreams",
  "ListServiceLevelObjectives",
  "ListServices",
  "ListTagsForResource",
  "PutAlarmMuteRule",
  "PutAnomalyDetector",
  "PutCompositeAlarm",
  "PutDashboard",
  "PutInsightRule",
  "PutLogAlarm",
  "PutManagedInsightRules",
  "PutMetricAlarm",
  "PutMetricData",
  "PutMetricStream",
  "SetAlarmState",
  "StartMetricStreams",
  "StartOTelEnrichment",
  "StopMetricStreams",
  "StopOTelEnrichment",
  "TagResource",
  "UntagResource",
  "UpdateServiceLevelObjective",
] as const;

export type CloudwatchAction = (typeof cloudwatchActions)[number];

export function cloudwatch(action: CloudwatchAction | "*"): `cloudwatch:${CloudwatchAction | "*"}` {
  return `cloudwatch:${action}` as `cloudwatch:${CloudwatchAction | "*"}`;
}
