export const cloudtrailActions = [
  "AddTags",
  "CancelQuery",
  "CreateChannel",
  "CreateDashboard",
  "CreateEventDataStore",
  "CreateServiceLinkedChannel",
  "CreateTrail",
  "DeleteChannel",
  "DeleteDashboard",
  "DeleteEventDataStore",
  "DeleteResourcePolicy",
  "DeleteServiceLinkedChannel",
  "DeleteTrail",
  "DeregisterOrganizationDelegatedAdmin",
  "DescribeQuery",
  "DescribeTrails",
  "DisableFederation",
  "EnableFederation",
  "GenerateQuery",
  "GenerateQueryResultsSummary",
  "GetChannel",
  "GetDashboard",
  "GetEventConfiguration",
  "GetEventDataStore",
  "GetEventDataStoreData",
  "GetEventSelectors",
  "GetImport",
  "GetInsightSelectors",
  "GetQueryResults",
  "GetResourcePolicy",
  "GetServiceLinkedChannel",
  "GetTrail",
  "GetTrailStatus",
  "ListChannels",
  "ListDashboards",
  "ListEventDataStores",
  "ListImportFailures",
  "ListImports",
  "ListInsightsData",
  "ListPublicKeys",
  "ListQueries",
  "ListServiceLinkedChannels",
  "ListTags",
  "ListTrails",
  "LookupEvents",
  "PutEventConfiguration",
  "PutEventSelectors",
  "PutInsightSelectors",
  "PutResourcePolicy",
  "RegisterOrganizationDelegatedAdmin",
  "RemoveTags",
  "RestoreEventDataStore",
  "SearchSampleQueries",
  "StartDashboardRefresh",
  "StartEventDataStoreIngestion",
  "StartImport",
  "StartLogging",
  "StartQuery",
  "StopEventDataStoreIngestion",
  "StopImport",
  "StopLogging",
  "UpdateChannel",
  "UpdateDashboard",
  "UpdateEventDataStore",
  "UpdateServiceLinkedChannel",
  "UpdateTrail",
] as const;

export type CloudtrailAction = (typeof cloudtrailActions)[number];

export function cloudtrail(action: CloudtrailAction | "*"): `cloudtrail:${CloudtrailAction | "*"}` {
  return `cloudtrail:${action}` as `cloudtrail:${CloudtrailAction | "*"}`;
}
