export const codepipelineActions = [
  "AcknowledgeJob",
  "AcknowledgeThirdPartyJob",
  "CreateCustomActionType",
  "CreatePipeline",
  "DeleteCustomActionType",
  "DeletePipeline",
  "DeleteWebhook",
  "DeregisterWebhookWithThirdParty",
  "DisableStageTransition",
  "EnableStageTransition",
  "GetActionType",
  "GetJobDetails",
  "GetPipeline",
  "GetPipelineExecution",
  "GetPipelineState",
  "GetThirdPartyJobDetails",
  "ListActionExecutions",
  "ListActionTypes",
  "ListDeployActionExecutionTargets",
  "ListPipelineExecutions",
  "ListPipelines",
  "ListRuleExecutions",
  "ListRuleTypes",
  "ListTagsForResource",
  "ListWebhooks",
  "OverrideStageCondition",
  "PollForJobs",
  "PollForThirdPartyJobs",
  "PutActionRevision",
  "PutApprovalResult",
  "PutJobFailureResult",
  "PutJobSuccessResult",
  "PutThirdPartyJobFailureResult",
  "PutThirdPartyJobSuccessResult",
  "PutWebhook",
  "RegisterWebhookWithThirdParty",
  "RetryStageExecution",
  "RollbackStage",
  "StartPipelineExecution",
  "StopPipelineExecution",
  "TagResource",
  "UntagResource",
  "UpdateActionType",
  "UpdatePipeline",
] as const;

export type CodepipelineAction = (typeof codepipelineActions)[number];

export function codepipeline(action: CodepipelineAction | "*"): `codepipeline:${CodepipelineAction | "*"}` {
  return `codepipeline:${action}` as `codepipeline:${CodepipelineAction | "*"}`;
}
