export const codeartifactActions = [
  "AssociateExternalConnection",
  "AssociateWithDownstreamRepository",
  "CopyPackageVersions",
  "CreateDomain",
  "CreatePackageGroup",
  "CreateRepository",
  "DeleteDomain",
  "DeleteDomainPermissionsPolicy",
  "DeletePackage",
  "DeletePackageGroup",
  "DeletePackageVersions",
  "DeleteRepository",
  "DeleteRepositoryPermissionsPolicy",
  "DescribeDomain",
  "DescribePackage",
  "DescribePackageGroup",
  "DescribePackageVersion",
  "DescribeRepository",
  "DisassociateExternalConnection",
  "DisposePackageVersions",
  "GetAssociatedPackageGroup",
  "GetAuthorizationToken",
  "GetDomainPermissionsPolicy",
  "GetPackageVersionAsset",
  "GetPackageVersionReadme",
  "GetRepositoryEndpoint",
  "GetRepositoryPermissionsPolicy",
  "ListAllowedRepositoriesForGroup",
  "ListAssociatedPackages",
  "ListDomains",
  "ListPackageGroups",
  "ListPackages",
  "ListPackageVersionAssets",
  "ListPackageVersionDependencies",
  "ListPackageVersions",
  "ListRepositories",
  "ListRepositoriesInDomain",
  "ListSubPackageGroups",
  "ListTagsForResource",
  "PublishPackageVersion",
  "PutDomainPermissionsPolicy",
  "PutPackageMetadata",
  "PutPackageOriginConfiguration",
  "PutRepositoryPermissionsPolicy",
  "ReadFromRepository",
  "TagResource",
  "UntagResource",
  "UpdatePackageGroup",
  "UpdatePackageGroupOriginConfiguration",
  "UpdatePackageVersionsStatus",
  "UpdateRepository",
] as const;

export type CodeartifactAction = (typeof codeartifactActions)[number];

export function codeartifact(action: CodeartifactAction | "*"): `codeartifact:${CodeartifactAction | "*"}` {
  return `codeartifact:${action}` as `codeartifact:${CodeartifactAction | "*"}`;
}
