export const codedeployActions = [
  "AddTagsToOnPremisesInstances",
  "BatchGetApplicationRevisions",
  "BatchGetApplications",
  "BatchGetDeploymentGroups",
  "BatchGetDeploymentInstances",
  "BatchGetDeployments",
  "BatchGetDeploymentTargets",
  "BatchGetOnPremisesInstances",
  "ContinueDeployment",
  "CreateApplication",
  "CreateCloudFormationDeployment",
  "CreateDeployment",
  "CreateDeploymentConfig",
  "CreateDeploymentGroup",
  "DeleteApplication",
  "DeleteDeploymentConfig",
  "DeleteDeploymentGroup",
  "DeleteGitHubAccountToken",
  "DeleteResourcesByExternalId",
  "DeregisterOnPremisesInstance",
  "GetApplication",
  "GetApplicationRevision",
  "GetDeployment",
  "GetDeploymentConfig",
  "GetDeploymentGroup",
  "GetDeploymentInstance",
  "GetDeploymentTarget",
  "GetOnPremisesInstance",
  "ListApplicationRevisions",
  "ListApplications",
  "ListDeploymentConfigs",
  "ListDeploymentGroups",
  "ListDeploymentInstances",
  "ListDeployments",
  "ListDeploymentTargets",
  "ListGitHubAccountTokenNames",
  "ListOnPremisesInstances",
  "ListTagsForResource",
  "PutLifecycleEventHookExecutionStatus",
  "RegisterApplicationRevision",
  "RegisterOnPremisesInstance",
  "RemoveTagsFromOnPremisesInstances",
  "SkipWaitTimeForInstanceTermination",
  "StopDeployment",
  "TagResource",
  "UntagResource",
  "UpdateApplication",
  "UpdateDeploymentGroup",
] as const;

export type CodedeployAction = (typeof codedeployActions)[number];

export function codedeploy(action: CodedeployAction | "*"): `codedeploy:${CodedeployAction | "*"}` {
  return `codedeploy:${action}` as `codedeploy:${CodedeployAction | "*"}`;
}
