export const codebuildActions = [
  "BatchDeleteBuilds",
  "BatchGetBuildBatches",
  "BatchGetBuilds",
  "BatchGetCommandExecutions",
  "BatchGetFleets",
  "BatchGetProjects",
  "BatchGetReportGroups",
  "BatchGetReports",
  "BatchGetSandboxes",
  "BatchPutCodeCoverages",
  "BatchPutTestCases",
  "CreateFleet",
  "CreateProject",
  "CreateReport",
  "CreateReportGroup",
  "CreateWebhook",
  "DeleteBuildBatch",
  "DeleteFleet",
  "DeleteOAuthToken",
  "DeleteProject",
  "DeleteReport",
  "DeleteReportGroup",
  "DeleteResourcePolicy",
  "DeleteSourceCredentials",
  "DeleteWebhook",
  "DescribeCodeCoverages",
  "DescribeTestCases",
  "GetReportGroupTrend",
  "GetResourcePolicy",
  "ImportSourceCredentials",
  "InvalidateProjectCache",
  "ListBuildBatches",
  "ListBuildBatchesForProject",
  "ListBuilds",
  "ListBuildsForProject",
  "ListCommandExecutionsForSandbox",
  "ListConnectedOAuthAccounts",
  "ListCuratedEnvironmentImages",
  "ListFleets",
  "ListProjects",
  "ListReportGroups",
  "ListReports",
  "ListReportsForReportGroup",
  "ListRepositories",
  "ListSandboxes",
  "ListSandboxesForProject",
  "ListSharedProjects",
  "ListSharedReportGroups",
  "ListSourceCredentials",
  "PersistOAuthToken",
  "PutResourcePolicy",
  "RetryBuild",
  "RetryBuildBatch",
  "StartBuild",
  "StartBuildBatch",
  "StartCommandExecution",
  "StartSandbox",
  "StartSandboxConnection",
  "StopBuild",
  "StopBuildBatch",
  "StopSandbox",
  "UpdateFleet",
  "UpdateProject",
  "UpdateProjectVisibility",
  "UpdateReport",
  "UpdateReportGroup",
  "UpdateWebhook",
] as const;

export type CodebuildAction = (typeof codebuildActions)[number];

export function codebuild(action: CodebuildAction | "*"): `codebuild:${CodebuildAction | "*"}` {
  return `codebuild:${action}` as `codebuild:${CodebuildAction | "*"}`;
}
