export const controltowerActions = [
  "CreateLandingZone",
  "CreateManagedAccount",
  "DeleteLandingZone",
  "DeregisterManagedAccount",
  "DeregisterOrganizationalUnit",
  "DescribeAccountFactoryConfig",
  "DescribeCoreService",
  "DescribeGuardrail",
  "DescribeGuardrailForTarget",
  "DescribeLandingZoneConfiguration",
  "DescribeManagedAccount",
  "DescribeManagedOrganizationalUnit",
  "DescribeRegisterOrganizationalUnitOperation",
  "DescribeSingleSignOn",
  "DisableBaseline",
  "DisableControl",
  "DisableGuardrail",
  "EnableBaseline",
  "EnableControl",
  "EnableGuardrail",
  "GetAccountInfo",
  "GetAvailableUpdates",
  "GetBaseline",
  "GetBaselineOperation",
  "GetControlOperation",
  "GetEnabledBaseline",
  "GetEnabledControl",
  "GetGuardrailComplianceStatus",
  "GetHomeRegion",
  "GetLandingZone",
  "GetLandingZoneDriftStatus",
  "GetLandingZoneOperation",
  "GetLandingZoneStatus",
  "ListBaselines",
  "ListControlOperations",
  "ListDirectoryGroups",
  "ListDriftDetails",
  "ListEnabledBaselines",
  "ListEnabledControls",
  "ListEnabledGuardrails",
  "ListExtendGovernancePrecheckDetails",
  "ListExternalConfigRuleCompliance",
  "ListGuardrails",
  "ListGuardrailsForTarget",
  "ListGuardrailViolations",
  "ListLandingZoneOperations",
  "ListLandingZones",
  "ListManagedAccounts",
  "ListManagedAccountsForGuardrail",
  "ListManagedAccountsForParent",
  "ListManagedOrganizationalUnits",
  "ListManagedOrganizationalUnitsForGuardrail",
  "ListTagsForResource",
  "ManageOrganizationalUnit",
  "PerformPreLaunchChecks",
  "ResetEnabledBaseline",
  "ResetEnabledControl",
  "ResetLandingZone",
  "SetupLandingZone",
  "TagResource",
  "UntagResource",
  "UpdateAccountFactoryConfig",
  "UpdateEnabledBaseline",
  "UpdateEnabledControl",
  "UpdateLandingZone",
] as const;

export type ControltowerAction = (typeof controltowerActions)[number];

export function controltower(action: ControltowerAction | "*"): `controltower:${ControltowerAction | "*"}` {
  return `controltower:${action}` as `controltower:${ControltowerAction | "*"}`;
}
