export const databrewActions = [
  "BatchDeleteRecipeVersion",
  "CreateDataset",
  "CreateProfileJob",
  "CreateProject",
  "CreateRecipe",
  "CreateRecipeJob",
  "CreateRuleset",
  "CreateSchedule",
  "DeleteDataset",
  "DeleteJob",
  "DeleteProject",
  "DeleteRecipeVersion",
  "DeleteRuleset",
  "DeleteSchedule",
  "DescribeDataset",
  "DescribeJob",
  "DescribeJobRun",
  "DescribeProject",
  "DescribeRecipe",
  "DescribeRuleset",
  "DescribeSchedule",
  "ListDatasets",
  "ListJobRuns",
  "ListJobs",
  "ListProjects",
  "ListRecipes",
  "ListRecipeVersions",
  "ListRulesets",
  "ListSchedules",
  "ListTagsForResource",
  "PublishRecipe",
  "SendProjectSessionAction",
  "StartJobRun",
  "StartProjectSession",
  "StopJobRun",
  "TagResource",
  "UntagResource",
  "UpdateDataset",
  "UpdateProfileJob",
  "UpdateProject",
  "UpdateRecipe",
  "UpdateRecipeJob",
  "UpdateRuleset",
  "UpdateSchedule",
] as const;

export type DatabrewAction = (typeof databrewActions)[number];

export function databrew(action: DatabrewAction | "*"): `databrew:${DatabrewAction | "*"}` {
  return `databrew:${action}` as `databrew:${DatabrewAction | "*"}`;
}
