export const datasyncActions = [
  "AddStorageSystem",
  "CancelTaskExecution",
  "CreateAgent",
  "CreateLocationAzureBlob",
  "CreateLocationEfs",
  "CreateLocationFsxLustre",
  "CreateLocationFsxOntap",
  "CreateLocationFsxOpenZfs",
  "CreateLocationFsxWindows",
  "CreateLocationHdfs",
  "CreateLocationNfs",
  "CreateLocationObjectStorage",
  "CreateLocationS3",
  "CreateLocationSmb",
  "CreateTask",
  "DeleteAgent",
  "DeleteLocation",
  "DeleteTask",
  "DescribeAgent",
  "DescribeDiscoveryJob",
  "DescribeLocationAzureBlob",
  "DescribeLocationEfs",
  "DescribeLocationFsxLustre",
  "DescribeLocationFsxOntap",
  "DescribeLocationFsxOpenZfs",
  "DescribeLocationFsxWindows",
  "DescribeLocationHdfs",
  "DescribeLocationNfs",
  "DescribeLocationObjectStorage",
  "DescribeLocationS3",
  "DescribeLocationSmb",
  "DescribeStorageSystem",
  "DescribeStorageSystemResourceMetrics",
  "DescribeStorageSystemResources",
  "DescribeTask",
  "DescribeTaskExecution",
  "GenerateRecommendations",
  "ListAgents",
  "ListDiscoveryJobs",
  "ListLocations",
  "ListStorageSystems",
  "ListTagsForResource",
  "ListTaskExecutions",
  "ListTasks",
  "RemoveStorageSystem",
  "StartDiscoveryJob",
  "StartTaskExecution",
  "StopDiscoveryJob",
  "TagResource",
  "UntagResource",
  "UpdateAgent",
  "UpdateDiscoveryJob",
  "UpdateLocationAzureBlob",
  "UpdateLocationEfs",
  "UpdateLocationFsxLustre",
  "UpdateLocationFsxOntap",
  "UpdateLocationFsxOpenZfs",
  "UpdateLocationFsxWindows",
  "UpdateLocationHdfs",
  "UpdateLocationNfs",
  "UpdateLocationObjectStorage",
  "UpdateLocationS3",
  "UpdateLocationSmb",
  "UpdateStorageSystem",
  "UpdateTask",
  "UpdateTaskExecution",
] as const;

export type DatasyncAction = (typeof datasyncActions)[number];

export function datasync(action: DatasyncAction | "*"): `datasync:${DatasyncAction | "*"}` {
  return `datasync:${action}` as `datasync:${DatasyncAction | "*"}`;
}
