export const ecrActions = [
  "BatchCheckLayerAvailability",
  "BatchDeleteImage",
  "BatchGetImage",
  "BatchGetRepositoryScanningConfiguration",
  "BatchImportUpstreamImage",
  "CompleteLayerUpload",
  "CreatePullThroughCacheRule",
  "CreateRepository",
  "CreateRepositoryCreationTemplate",
  "DeleteLifecyclePolicy",
  "DeletePullThroughCacheRule",
  "DeleteRegistryPolicy",
  "DeleteRepository",
  "DeleteRepositoryCreationTemplate",
  "DeleteRepositoryPolicy",
  "DeleteSigningConfiguration",
  "DeregisterPullTimeUpdateExclusion",
  "DescribeImageReplicationStatus",
  "DescribeImages",
  "DescribeImageScanFindings",
  "DescribeImageSigningStatus",
  "DescribePullThroughCacheRules",
  "DescribeRegistry",
  "DescribeRepositories",
  "DescribeRepositoryCreationTemplates",
  "GetAccountSetting",
  "GetAuthorizationToken",
  "GetDownloadUrlForLayer",
  "GetImageCopyStatus",
  "GetLifecyclePolicy",
  "GetLifecyclePolicyPreview",
  "GetRegistryPolicy",
  "GetRegistryScanningConfiguration",
  "GetRepositoryPolicy",
  "GetSigningConfiguration",
  "InitiateLayerUpload",
  "ListImages",
  "ListPullTimeUpdateExclusions",
  "ListTagsForResource",
  "PutAccountSetting",
  "PutImage",
  "PutImageScanningConfiguration",
  "PutImageTagMutability",
  "PutLifecyclePolicy",
  "PutRegistryPolicy",
  "PutRegistryScanningConfiguration",
  "PutReplicationConfiguration",
  "PutSigningConfiguration",
  "RegisterPullTimeUpdateExclusion",
  "ReplicateImage",
  "SetRepositoryPolicy",
  "StartImageScan",
  "StartLifecyclePolicyPreview",
  "TagResource",
  "UntagResource",
  "UpdateImageStorageClass",
  "UpdatePullThroughCacheRule",
  "UpdateRepositoryCreationTemplate",
  "UploadLayerPart",
  "ValidatePullThroughCacheRule",
] as const;

export type EcrAction = (typeof ecrActions)[number];

export function ecr(action: EcrAction | "*"): `ecr:${EcrAction | "*"}` {
  return `ecr:${action}` as `ecr:${EcrAction | "*"}`;
}
