export const eksActions = [
  "AccessKubernetesApi",
  "AssociateAccessPolicy",
  "AssociateEncryptionConfig",
  "AssociateIdentityProviderConfig",
  "CancelUpdate",
  "CreateAccessEntry",
  "CreateAddon",
  "CreateCapability",
  "CreateCluster",
  "CreateEksAnywhereSubscription",
  "CreateFargateProfile",
  "CreateNodegroup",
  "CreatePodIdentityAssociation",
  "DeleteAccessEntry",
  "DeleteAddon",
  "DeleteCapability",
  "DeleteCluster",
  "DeleteEksAnywhereSubscription",
  "DeleteFargateProfile",
  "DeleteNodegroup",
  "DeletePodIdentityAssociation",
  "DeregisterCluster",
  "DescribeAccessEntry",
  "DescribeAddon",
  "DescribeAddonConfiguration",
  "DescribeAddonVersions",
  "DescribeCapability",
  "DescribeCluster",
  "DescribeClusterVersions",
  "DescribeEksAnywhereSubscription",
  "DescribeFargateProfile",
  "DescribeIdentityProviderConfig",
  "DescribeInsight",
  "DescribeInsightsRefresh",
  "DescribeNodegroup",
  "DescribePodIdentityAssociation",
  "DescribeUpdate",
  "DisassociateAccessPolicy",
  "DisassociateIdentityProviderConfig",
  "ListAccessEntries",
  "ListAccessPolicies",
  "ListAddons",
  "ListAssociatedAccessPolicies",
  "ListCapabilities",
  "ListClusters",
  "ListDashboardData",
  "ListDashboardResources",
  "ListEksAnywhereSubscriptions",
  "ListFargateProfiles",
  "ListIdentityProviderConfigs",
  "ListInsights",
  "ListNodegroups",
  "ListPodIdentityAssociations",
  "ListTagsForResource",
  "ListUpdates",
  "MutateViaKubernetesApi",
  "RegisterCluster",
  "StartInsightsRefresh",
  "TagResource",
  "UntagResource",
  "UpdateAccessEntry",
  "UpdateAddon",
  "UpdateCapability",
  "UpdateClusterConfig",
  "UpdateClusterVersion",
  "UpdateEksAnywhereSubscription",
  "UpdateNodegroupConfig",
  "UpdateNodegroupVersion",
  "UpdatePodIdentityAssociation",
] as const;

export type EksAction = (typeof eksActions)[number];

export function eks(action: EksAction | "*"): `eks:${EksAction | "*"}` {
  return `eks:${action}` as `eks:${EksAction | "*"}`;
}
