export const elasticloadbalancingActions = [
  "AddListenerCertificates",
  "AddTags",
  "AddTrustStoreRevocations",
  "AllowVendedLogDeliveryForResource",
  "CreateListener",
  "CreateLoadBalancer",
  "CreateRule",
  "CreateTargetGroup",
  "CreateTrustStore",
  "CreateWebACLAssociation",
  "DeleteListener",
  "DeleteLoadBalancer",
  "DeleteRule",
  "DeleteSharedTrustStoreAssociation",
  "DeleteTargetGroup",
  "DeleteTrustStore",
  "DeleteWebACLAssociation",
  "DeregisterTargets",
  "DescribeAccountLimits",
  "DescribeCapacityReservation",
  "DescribeListenerAttributes",
  "DescribeListenerCertificates",
  "DescribeListeners",
  "DescribeLoadBalancerAttributes",
  "DescribeLoadBalancers",
  "DescribeRules",
  "DescribeSSLPolicies",
  "DescribeTags",
  "DescribeTargetGroupAttributes",
  "DescribeTargetGroups",
  "DescribeTargetHealth",
  "DescribeTrustStoreAssociations",
  "DescribeTrustStoreRevocations",
  "DescribeTrustStores",
  "DescribeWebACLAssociation",
  "GetLoadBalancerWebACL",
  "GetResourcePolicy",
  "GetTrustStoreCaCertificatesBundle",
  "GetTrustStoreRevocationContent",
  "ModifyCapacityReservation",
  "ModifyIpPools",
  "ModifyListener",
  "ModifyListenerAttributes",
  "ModifyLoadBalancerAttributes",
  "ModifyRule",
  "ModifyTargetGroup",
  "ModifyTargetGroupAttributes",
  "ModifyTrustStore",
  "RegisterTargets",
  "RemoveListenerCertificates",
  "RemoveTags",
  "RemoveTrustStoreRevocations",
  "SetIpAddressType",
  "SetRulePriorities",
  "SetSecurityGroups",
  "SetSubnets",
  "SetWebAcl",
] as const;

export type ElasticloadbalancingAction = (typeof elasticloadbalancingActions)[number];

export function elasticloadbalancing(action: ElasticloadbalancingAction | "*"): `elasticloadbalancing:${ElasticloadbalancingAction | "*"}` {
  return `elasticloadbalancing:${action}` as `elasticloadbalancing:${ElasticloadbalancingAction | "*"}`;
}
