export const elasticbeanstalkActions = [
  "AbortEnvironmentUpdate",
  "AddTags",
  "ApplyEnvironmentManagedAction",
  "AssociateEnvironmentOperationsRole",
  "CheckDNSAvailability",
  "ComposeEnvironments",
  "CreateApplication",
  "CreateApplicationVersion",
  "CreateConfigurationTemplate",
  "CreateEnvironment",
  "CreatePlatformVersion",
  "CreateStorageLocation",
  "DeleteApplication",
  "DeleteApplicationVersion",
  "DeleteConfigurationTemplate",
  "DeleteEnvironmentConfiguration",
  "DeletePlatformVersion",
  "DescribeAccountAttributes",
  "DescribeApplications",
  "DescribeApplicationVersions",
  "DescribeConfigurationOptions",
  "DescribeConfigurationSettings",
  "DescribeEnvironmentHealth",
  "DescribeEnvironmentManagedActionHistory",
  "DescribeEnvironmentManagedActions",
  "DescribeEnvironmentResources",
  "DescribeEnvironments",
  "DescribeEvents",
  "DescribeInstancesHealth",
  "DescribePlatformVersion",
  "DisassociateEnvironmentOperationsRole",
  "ListAvailableSolutionStacks",
  "ListPlatformBranches",
  "ListPlatformVersions",
  "ListTagsForResource",
  "PutInstanceStatistics",
  "RebuildEnvironment",
  "RemoveTags",
  "RequestEnvironmentInfo",
  "RestartAppServer",
  "RetrieveEnvironmentInfo",
  "SwapEnvironmentCNAMEs",
  "TerminateEnvironment",
  "UpdateApplication",
  "UpdateApplicationResourceLifecycle",
  "UpdateApplicationVersion",
  "UpdateConfigurationTemplate",
  "UpdateEnvironment",
  "UpdateTagsForResource",
  "ValidateConfigurationSettings",
] as const;

export type ElasticbeanstalkAction = (typeof elasticbeanstalkActions)[number];

export function elasticbeanstalk(action: ElasticbeanstalkAction | "*"): `elasticbeanstalk:${ElasticbeanstalkAction | "*"}` {
  return `elasticbeanstalk:${action}` as `elasticbeanstalk:${ElasticbeanstalkAction | "*"}`;
}
