export const eventsActions = [
  "ActivateEventSource",
  "AllowVendedLogDeliveryForResource",
  "CancelReplay",
  "CreateApiDestination",
  "CreateArchive",
  "CreateConnection",
  "CreateEndpoint",
  "CreateEventBus",
  "CreatePartnerEventSource",
  "DeactivateEventSource",
  "DeauthorizeConnection",
  "DeleteApiDestination",
  "DeleteArchive",
  "DeleteConnection",
  "DeleteEndpoint",
  "DeleteEventBus",
  "DeletePartnerEventSource",
  "DeleteRule",
  "DescribeApiDestination",
  "DescribeArchive",
  "DescribeConnection",
  "DescribeEndpoint",
  "DescribeEventBus",
  "DescribeEventSource",
  "DescribePartnerEventSource",
  "DescribeReplay",
  "DescribeRule",
  "DisableRule",
  "EnableRule",
  "InvokeApiDestination",
  "ListApiDestinations",
  "ListArchives",
  "ListConnections",
  "ListEndpoints",
  "ListEventBuses",
  "ListEventSources",
  "ListPartnerEventSourceAccounts",
  "ListPartnerEventSources",
  "ListReplays",
  "ListRuleNamesByTarget",
  "ListRules",
  "ListTagsForResource",
  "ListTargetsByRule",
  "PutEvents",
  "PutPartnerEvents",
  "PutPermission",
  "PutRule",
  "PutTargets",
  "RemovePermission",
  "RemoveTargets",
  "RetrieveConnectionCredentials",
  "StartReplay",
  "TagResource",
  "TestEventPattern",
  "UntagResource",
  "UpdateApiDestination",
  "UpdateArchive",
  "UpdateConnection",
  "UpdateEndpoint",
  "UpdateEventBus",
] as const;

export type EventsAction = (typeof eventsActions)[number];

export function events(action: EventsAction | "*"): `events:${EventsAction | "*"}` {
  return `events:${action}` as `events:${EventsAction | "*"}`;
}
