export const finopsAgentActions = [
  "AcceptAgentRequest",
  "CancelTask",
  "CancelTurn",
  "CreateAgentSpace",
  "CreateAutomation",
  "CreateConnection",
  "CreateConversation",
  "CreateDocument",
  "CreateIntegration",
  "CreateOneTimeLoginSession",
  "CreateTask",
  "CreateTurn",
  "DeleteAgentSpace",
  "DeleteArtifact",
  "DeleteAutomation",
  "DeleteConnection",
  "DeleteDocument",
  "DeleteIntegration",
  "GetAgentRequest",
  "GetAgentSpace",
  "GetArtifactContent",
  "GetArtifactMetadata",
  "GetAutomation",
  "GetConnection",
  "GetDocumentContent",
  "GetDocumentMetadata",
  "GetIntegration",
  "GetTask",
  "GetTurn",
  "ListAgentSpaces",
  "ListArtifacts",
  "ListAutomations",
  "ListConnections",
  "ListConversations",
  "ListDocuments",
  "ListIntegrations",
  "ListRecords",
  "ListTasks",
  "ListTurns",
  "RejectAgentRequest",
  "RestoreDocument",
  "SendFeedback",
  "UpdateAgentSpace",
  "UpdateAutomation",
  "UpdateConnection",
  "UpdateDocument",
] as const;

export type FinopsAgentAction = (typeof finopsAgentActions)[number];

export function finopsAgent(action: FinopsAgentAction | "*"): `finops-agent:${FinopsAgentAction | "*"}` {
  return `finops-agent:${action}` as `finops-agent:${FinopsAgentAction | "*"}`;
}
