export const finspaceActions = [
  "ConnectKxCluster",
  "CreateEnvironment",
  "CreateKxChangeset",
  "CreateKxCluster",
  "CreateKxDatabase",
  "CreateKxDataview",
  "CreateKxEnvironment",
  "CreateKxScalingGroup",
  "CreateKxUser",
  "CreateKxVolume",
  "CreateUser",
  "DeleteEnvironment",
  "DeleteKxCluster",
  "DeleteKxClusterNode",
  "DeleteKxDatabase",
  "DeleteKxDataview",
  "DeleteKxEnvironment",
  "DeleteKxScalingGroup",
  "DeleteKxUser",
  "DeleteKxVolume",
  "GetEnvironment",
  "GetKxChangeset",
  "GetKxCluster",
  "GetKxConnectionString",
  "GetKxDatabase",
  "GetKxDataview",
  "GetKxEnvironment",
  "GetKxScalingGroup",
  "GetKxUser",
  "GetKxVolume",
  "GetLoadSampleDataSetGroupIntoEnvironmentStatus",
  "GetUser",
  "ListEnvironments",
  "ListKxChangesets",
  "ListKxClusterNodes",
  "ListKxClusters",
  "ListKxDatabases",
  "ListKxDataviews",
  "ListKxEnvironments",
  "ListKxScalingGroups",
  "ListKxUsers",
  "ListKxVolumes",
  "ListTagsForResource",
  "ListUsers",
  "LoadSampleDataSetGroupIntoEnvironment",
  "MountKxDatabase",
  "ResetUserPassword",
  "TagResource",
  "UntagResource",
  "UpdateEnvironment",
  "UpdateKxClusterCodeConfiguration",
  "UpdateKxClusterDatabases",
  "UpdateKxDatabase",
  "UpdateKxDataview",
  "UpdateKxEnvironment",
  "UpdateKxEnvironmentNetwork",
  "UpdateKxUser",
  "UpdateKxVolume",
  "UpdateUser",
] as const;

export type FinspaceAction = (typeof finspaceActions)[number];

export function finspace(action: FinspaceAction | "*"): `finspace:${FinspaceAction | "*"}` {
  return `finspace:${action}` as `finspace:${FinspaceAction | "*"}`;
}
