export const fmsActions = [
  "AssociateAdminAccount",
  "AssociateThirdPartyFirewall",
  "BatchAssociateResource",
  "BatchDisassociateResource",
  "DeleteAppsList",
  "DeleteNotificationChannel",
  "DeletePolicy",
  "DeleteProtocolsList",
  "DeleteResourceSet",
  "DisassociateAdminAccount",
  "DisassociateThirdPartyFirewall",
  "GetAdminAccount",
  "GetAdminScope",
  "GetAppsList",
  "GetComplianceDetail",
  "GetNotificationChannel",
  "GetPolicy",
  "GetProtectionStatus",
  "GetProtocolsList",
  "GetResourceSet",
  "GetThirdPartyFirewallAssociationStatus",
  "GetViolationDetails",
  "ListAdminAccountsForOrganization",
  "ListAdminsManagingAccount",
  "ListAppsLists",
  "ListComplianceStatus",
  "ListDiscoveredResources",
  "ListMemberAccounts",
  "ListPolicies",
  "ListProtocolsLists",
  "ListResourceSetResources",
  "ListResourceSets",
  "ListTagsForResource",
  "ListThirdPartyFirewallFirewallPolicies",
  "PutAdminAccount",
  "PutAppsList",
  "PutNotificationChannel",
  "PutPolicy",
  "PutProtocolsList",
  "PutResourceSet",
  "TagResource",
  "UntagResource",
] as const;

export type FmsAction = (typeof fmsActions)[number];

export function fms(action: FmsAction | "*"): `fms:${FmsAction | "*"}` {
  return `fms:${action}` as `fms:${FmsAction | "*"}`;
}
