export const fsxActions = [
  "AssociateFileGateway",
  "AssociateFileSystemAliases",
  "BypassSnaplockEnterpriseRetention",
  "CancelDataRepositoryTask",
  "CopyBackup",
  "CopySnapshotAndUpdateVolume",
  "CreateAndAttachS3AccessPoint",
  "CreateBackup",
  "CreateDataRepositoryAssociation",
  "CreateDataRepositoryTask",
  "CreateFileCache",
  "CreateFileSystem",
  "CreateFileSystemFromBackup",
  "CreateSnapshot",
  "CreateStorageVirtualMachine",
  "CreateVolume",
  "CreateVolumeFromBackup",
  "DeleteBackup",
  "DeleteDataRepositoryAssociation",
  "DeleteFileCache",
  "DeleteFileSystem",
  "DeleteResourcePolicy",
  "DeleteSnapshot",
  "DeleteStorageVirtualMachine",
  "DeleteVolume",
  "DescribeAssociatedFileGateways",
  "DescribeBackups",
  "DescribeDataRepositoryAssociations",
  "DescribeDataRepositoryTasks",
  "DescribeFileCaches",
  "DescribeFileSystemAliases",
  "DescribeFileSystems",
  "DescribeS3AccessPointAttachments",
  "DescribeSharedVpcConfiguration",
  "DescribeSnapshots",
  "DescribeStorageVirtualMachines",
  "DescribeVolumes",
  "DetachAndDeleteS3AccessPoint",
  "DisassociateFileGateway",
  "DisassociateFileSystemAliases",
  "GetResourcePolicy",
  "ListTagsForResource",
  "ManageBackupPrincipalAssociations",
  "PutResourcePolicy",
  "ReleaseFileSystemNfsV3Locks",
  "RestoreVolumeFromSnapshot",
  "StartMisconfiguredStateRecovery",
  "TagResource",
  "UntagResource",
  "UpdateDataRepositoryAssociation",
  "UpdateFileCache",
  "UpdateFileSystem",
  "UpdateSharedVpcConfiguration",
  "UpdateSnapshot",
  "UpdateStorageVirtualMachine",
  "UpdateVolume",
] as const;

export type FsxAction = (typeof fsxActions)[number];

export function fsx(action: FsxAction | "*"): `fsx:${FsxAction | "*"}` {
  return `fsx:${action}` as `fsx:${FsxAction | "*"}`;
}
