export const geoActions = [
  "AssociateTrackerConsumer",
  "BatchDeleteDevicePositionHistory",
  "BatchDeleteGeofence",
  "BatchEvaluateGeofences",
  "BatchGetDevicePosition",
  "BatchPutGeofence",
  "BatchUpdateDevicePosition",
  "CalculateRoute",
  "CalculateRouteMatrix",
  "CancelJob",
  "CreateGeofenceCollection",
  "CreateKey",
  "CreateMap",
  "CreatePlaceIndex",
  "CreateRouteCalculator",
  "CreateTracker",
  "DeleteGeofenceCollection",
  "DeleteKey",
  "DeleteMap",
  "DeletePlaceIndex",
  "DeleteRouteCalculator",
  "DeleteTracker",
  "DescribeGeofenceCollection",
  "DescribeKey",
  "DescribeMap",
  "DescribePlaceIndex",
  "DescribeRouteCalculator",
  "DescribeTracker",
  "DisassociateTrackerConsumer",
  "ForecastGeofenceEvents",
  "GetDevicePosition",
  "GetDevicePositionHistory",
  "GetGeofence",
  "GetJob",
  "GetMapGlyphs",
  "GetMapSprites",
  "GetMapStyleDescriptor",
  "GetMapTile",
  "GetPlace",
  "ListDevicePositions",
  "ListGeofenceCollections",
  "ListGeofences",
  "ListJobs",
  "ListKeys",
  "ListMaps",
  "ListPlaceIndexes",
  "ListRouteCalculators",
  "ListTagsForResource",
  "ListTrackerConsumers",
  "ListTrackers",
  "PutGeofence",
  "SearchPlaceIndexForPosition",
  "SearchPlaceIndexForSuggestions",
  "SearchPlaceIndexForText",
  "StartJob",
  "TagResource",
  "UntagResource",
  "UpdateGeofenceCollection",
  "UpdateKey",
  "UpdateMap",
  "UpdatePlaceIndex",
  "UpdateRouteCalculator",
  "UpdateTracker",
  "VerifyDevicePosition",
] as const;

export type GeoAction = (typeof geoActions)[number];

export function geo(action: GeoAction | "*"): `geo:${GeoAction | "*"}` {
  return `geo:${action}` as `geo:${GeoAction | "*"}`;
}
