export const globalacceleratorActions = [
  "AddCustomRoutingEndpoints",
  "AddEndpoints",
  "AdvertiseByoipCidr",
  "AllowCustomRoutingTraffic",
  "CreateAccelerator",
  "CreateCrossAccountAttachment",
  "CreateCustomRoutingAccelerator",
  "CreateCustomRoutingEndpointGroup",
  "CreateCustomRoutingListener",
  "CreateEndpointGroup",
  "CreateListener",
  "DeleteAccelerator",
  "DeleteCrossAccountAttachment",
  "DeleteCustomRoutingAccelerator",
  "DeleteCustomRoutingEndpointGroup",
  "DeleteCustomRoutingListener",
  "DeleteEndpointGroup",
  "DeleteListener",
  "DenyCustomRoutingTraffic",
  "DeprovisionByoipCidr",
  "DescribeAccelerator",
  "DescribeAcceleratorAttributes",
  "DescribeCrossAccountAttachment",
  "DescribeCustomRoutingAccelerator",
  "DescribeCustomRoutingAcceleratorAttributes",
  "DescribeCustomRoutingEndpointGroup",
  "DescribeCustomRoutingListener",
  "DescribeEndpointGroup",
  "DescribeListener",
  "ListAccelerators",
  "ListByoipCidrs",
  "ListCrossAccountAttachments",
  "ListCrossAccountResourceAccounts",
  "ListCrossAccountResources",
  "ListCustomRoutingAccelerators",
  "ListCustomRoutingEndpointGroups",
  "ListCustomRoutingListeners",
  "ListCustomRoutingPortMappings",
  "ListCustomRoutingPortMappingsByDestination",
  "ListEndpointGroups",
  "ListListeners",
  "ListTagsForResource",
  "ProvisionByoipCidr",
  "RemoveCustomRoutingEndpoints",
  "RemoveEndpoints",
  "TagResource",
  "UntagResource",
  "UpdateAccelerator",
  "UpdateAcceleratorAttributes",
  "UpdateCrossAccountAttachment",
  "UpdateCustomRoutingAccelerator",
  "UpdateCustomRoutingAcceleratorAttributes",
  "UpdateCustomRoutingListener",
  "UpdateEndpointGroup",
  "UpdateListener",
  "WithdrawByoipCidr",
] as const;

export type GlobalacceleratorAction = (typeof globalacceleratorActions)[number];

export function globalaccelerator(action: GlobalacceleratorAction | "*"): `globalaccelerator:${GlobalacceleratorAction | "*"}` {
  return `globalaccelerator:${action}` as `globalaccelerator:${GlobalacceleratorAction | "*"}`;
}
