export const healthAgentActions = [
  "ActivateSubscription",
  "CancelAppointment",
  "CreateAgent",
  "CreateDomain",
  "CreateIntegration",
  "CreateSession",
  "CreateSubscription",
  "DeactivateSubscription",
  "DeleteAgent",
  "DeleteDomain",
  "DeleteIntegration",
  "GetAgent",
  "GetCareTeamProvider",
  "GetDomain",
  "GetDomainAnalytics",
  "GetIntegration",
  "GetMedicalScribeListeningSession",
  "GetPatient",
  "GetPatientInsightsJob",
  "GetPractitioner",
  "GetSessionContext",
  "GetSubscription",
  "InvokeAgent",
  "ListAgents",
  "ListAppointmentSlots",
  "ListDomains",
  "ListIntegrations",
  "ListPatientAppointments",
  "ListPatientInsuranceCoverages",
  "ListPatientMedications",
  "ListProviders",
  "ListSessionRecords",
  "ListSubscriptions",
  "ListTagsForResource",
  "MatchPatient",
  "PublishAgent",
  "RescheduleAppointment",
  "ResetPassword",
  "ScheduleAppointment",
  "StartMedicalScribeListeningSession",
  "StartPatientInsightsJob",
  "SubmitMedicationRenewal",
  "TagResource",
  "UntagResource",
  "UpdateAgent",
  "UpdateIntegration",
  "UpdateSession",
] as const;

export type HealthAgentAction = (typeof healthAgentActions)[number];

export function healthAgent(action: HealthAgentAction | "*"): `health-agent:${HealthAgentAction | "*"}` {
  return `health-agent:${action}` as `health-agent:${HealthAgentAction | "*"}`;
}
