export const healthlakeActions = [
  "CancelFHIRExportJobWithDelete",
  "ConfirmAttributionList",
  "CreateFHIRDatastore",
  "CreateResource",
  "DeleteFHIRDatastore",
  "DeleteResource",
  "DescribeFHIRBulkDeleteJob",
  "DescribeFHIRBulkMemberMatchJob",
  "DescribeFHIRDatastore",
  "DescribeFHIRExportJob",
  "DescribeFHIRExportJobWithGet",
  "DescribeFHIRImportJob",
  "ExpandValueSetWithGet",
  "ExpandValueSetWithPost",
  "GenerateDocumentWithGet",
  "GenerateDocumentWithPost",
  "GetCapabilities",
  "GetExportedFile",
  "GetHistoryByResourceId",
  "InquirePreAuthClaim",
  "ListFHIRDatastores",
  "ListFHIRExportJobs",
  "ListFHIRImportJobs",
  "ListTagsForResource",
  "LookupCodeSystemWithGet",
  "LookupCodeSystemWithPost",
  "MemberAdd",
  "MemberMatch",
  "MemberRemove",
  "PatchResource",
  "ProcessBundle",
  "QuestionnairePackage",
  "ReadResource",
  "RetrieveAttributionStatus",
  "SearchEverything",
  "SearchWithGet",
  "SearchWithPost",
  "StartFHIRBulkDeleteJob",
  "StartFHIRBulkMemberMatchJob",
  "StartFHIRExportJob",
  "StartFHIRExportJobWithGet",
  "StartFHIRExportJobWithPost",
  "StartFHIRImportJob",
  "SubmitPreAuthClaim",
  "TagResource",
  "UntagResource",
  "UpdateFHIRDatastore",
  "UpdateResource",
  "ValidateResource",
  "VersionReadResource",
] as const;

export type HealthlakeAction = (typeof healthlakeActions)[number];

export function healthlake(action: HealthlakeAction | "*"): `healthlake:${HealthlakeAction | "*"}` {
  return `healthlake:${action}` as `healthlake:${HealthlakeAction | "*"}`;
}
