export const iotfleetwiseActions = [
  "AssociateVehicleFleet",
  "CreateCampaign",
  "CreateDecoderManifest",
  "CreateFleet",
  "CreateModelManifest",
  "CreateSignalCatalog",
  "CreateStateTemplate",
  "CreateVehicle",
  "DeleteCampaign",
  "DeleteDecoderManifest",
  "DeleteFleet",
  "DeleteModelManifest",
  "DeleteSignalCatalog",
  "DeleteStateTemplate",
  "DeleteVehicle",
  "DisassociateVehicleFleet",
  "GenerateCommandPayload",
  "GetCampaign",
  "GetDecoderManifest",
  "GetEncryptionConfiguration",
  "GetFleet",
  "GetLoggingOptions",
  "GetModelManifest",
  "GetRegisterAccountStatus",
  "GetSignalCatalog",
  "GetStateTemplate",
  "GetVehicle",
  "GetVehicleStatus",
  "ImportDecoderManifest",
  "ImportSignalCatalog",
  "ListCampaigns",
  "ListDecoderManifestNetworkInterfaces",
  "ListDecoderManifests",
  "ListDecoderManifestSignals",
  "ListFleets",
  "ListFleetsForVehicle",
  "ListModelManifestNodes",
  "ListModelManifests",
  "ListSignalCatalogNodes",
  "ListSignalCatalogs",
  "ListStateTemplates",
  "ListTagsForResource",
  "ListVehicles",
  "ListVehiclesInFleet",
  "PutEncryptionConfiguration",
  "PutLoggingOptions",
  "RegisterAccount",
  "TagResource",
  "UntagResource",
  "UpdateCampaign",
  "UpdateDecoderManifest",
  "UpdateFleet",
  "UpdateModelManifest",
  "UpdateSignalCatalog",
  "UpdateStateTemplate",
  "UpdateVehicle",
] as const;

export type IotfleetwiseAction = (typeof iotfleetwiseActions)[number];

export function iotfleetwise(action: IotfleetwiseAction | "*"): `iotfleetwise:${IotfleetwiseAction | "*"}` {
  return `iotfleetwise:${action}` as `iotfleetwise:${IotfleetwiseAction | "*"}`;
}
