export const iqActions = [
  "AcceptCall",
  "ApprovePaymentRequest",
  "ApproveProposal",
  "ArchiveConversation",
  "CompleteProposal",
  "CreateConversation",
  "CreateExpert",
  "CreateListing",
  "CreateMilestoneProposal",
  "CreatePaymentRequest",
  "CreateProject",
  "CreateRequest",
  "CreateScheduledProposal",
  "CreateSeller",
  "CreateUpfrontProposal",
  "DeclineCall",
  "DeleteAttachment",
  "DisableIndividualPublicProfile",
  "DownloadAttachment",
  "EnableIndividualPublicProfile",
  "EndCall",
  "GetBuyer",
  "GetCall",
  "GetChatInfo",
  "GetChatMessages",
  "GetChatToken",
  "GetCompanyChatMessages",
  "GetCompanyProfile",
  "GetConversation",
  "GetExpert",
  "GetListing",
  "GetMarketplaceSeller",
  "GetPaymentRequest",
  "GetProposal",
  "GetRequest",
  "GetReview",
  "HideRequest",
  "InitiateCall",
  "LinkAwsCertification",
  "ListAttachments",
  "ListConversations",
  "ListExpertAccessLogs",
  "ListListings",
  "ListPaymentRequests",
  "ListProposals",
  "ListRequests",
  "ListReviews",
  "MarkChatMessageRead",
  "RejectPaymentRequest",
  "RejectProposal",
  "SendCompanyChatMessage",
  "SendIndividualChatMessage",
  "UnarchiveConversation",
  "UnlinkAwsCertification",
  "UpdateCompanyProfile",
  "UpdateConversationMembers",
  "UpdateExpert",
  "UpdateListing",
  "UpdateRequest",
  "UploadAttachment",
  "WithdrawPaymentRequest",
  "WithdrawProposal",
  "WriteReview",
] as const;

export type IqAction = (typeof iqActions)[number];

export function iq(action: IqAction | "*"): `iq:${IqAction | "*"}` {
  return `iq:${action}` as `iq:${IqAction | "*"}`;
}
