export const kafkaActions = [
  "BatchAssociateScramSecret",
  "BatchDisassociateScramSecret",
  "CreateCluster",
  "CreateClusterV2",
  "CreateConfiguration",
  "CreateReplicator",
  "CreateTopic",
  "CreateVpcConnection",
  "DeleteCluster",
  "DeleteClusterPolicy",
  "DeleteConfiguration",
  "DeleteReplicator",
  "DeleteTopic",
  "DeleteVpcConnection",
  "DescribeCluster",
  "DescribeClusterOperation",
  "DescribeClusterOperationV2",
  "DescribeClusterV2",
  "DescribeConfiguration",
  "DescribeConfigurationRevision",
  "DescribeReplicator",
  "DescribeTopic",
  "DescribeTopicPartitions",
  "DescribeVpcConnection",
  "GetBootstrapBrokers",
  "GetClusterPolicy",
  "GetCompatibleKafkaVersions",
  "ListClientVpcConnections",
  "ListClusterOperations",
  "ListClusterOperationsV2",
  "ListClusters",
  "ListClustersV2",
  "ListConfigurationRevisions",
  "ListConfigurations",
  "ListKafkaVersions",
  "ListNodes",
  "ListReplicators",
  "ListScramSecrets",
  "ListTagsForResource",
  "ListTopics",
  "ListVpcConnections",
  "PutClusterPolicy",
  "RebootBroker",
  "RejectClientVpcConnection",
  "TagResource",
  "UntagResource",
  "UpdateBrokerCount",
  "UpdateBrokerStorage",
  "UpdateBrokerType",
  "UpdateClusterConfiguration",
  "UpdateClusterKafkaVersion",
  "UpdateConfiguration",
  "UpdateConnectivity",
  "UpdateMonitoring",
  "UpdateRebalancing",
  "UpdateReplicationInfo",
  "UpdateSecurity",
  "UpdateStorage",
  "UpdateTopic",
] as const;

export type KafkaAction = (typeof kafkaActions)[number];

export function kafka(action: KafkaAction | "*"): `kafka:${KafkaAction | "*"}` {
  return `kafka:${action}` as `kafka:${KafkaAction | "*"}`;
}
