export const kendraActions = [
  "AssociateEntitiesToExperience",
  "AssociatePersonasToEntities",
  "BatchDeleteDocument",
  "BatchDeleteFeaturedResultsSet",
  "BatchGetDocumentStatus",
  "BatchPutDocument",
  "ClearQuerySuggestions",
  "CreateAccessControlConfiguration",
  "CreateDataSource",
  "CreateExperience",
  "CreateFaq",
  "CreateFeaturedResultsSet",
  "CreateIndex",
  "CreateQuerySuggestionsBlockList",
  "CreateThesaurus",
  "DeleteAccessControlConfiguration",
  "DeleteDataSource",
  "DeleteExperience",
  "DeleteFaq",
  "DeleteIndex",
  "DeletePrincipalMapping",
  "DeleteQuerySuggestionsBlockList",
  "DeleteThesaurus",
  "DescribeAccessControlConfiguration",
  "DescribeDataSource",
  "DescribeExperience",
  "DescribeFaq",
  "DescribeFeaturedResultsSet",
  "DescribeIndex",
  "DescribePrincipalMapping",
  "DescribeQuerySuggestionsBlockList",
  "DescribeQuerySuggestionsConfig",
  "DescribeThesaurus",
  "DisassociateEntitiesFromExperience",
  "DisassociatePersonasFromEntities",
  "GetQuerySuggestions",
  "GetSnapshots",
  "ListAccessControlConfigurations",
  "ListDataSources",
  "ListDataSourceSyncJobs",
  "ListEntityPersonas",
  "ListExperienceEntities",
  "ListExperiences",
  "ListFaqs",
  "ListFeaturedResultsSets",
  "ListGroupsOlderThanOrderingId",
  "ListIndices",
  "ListQuerySuggestionsBlockLists",
  "ListTagsForResource",
  "ListThesauri",
  "PutPrincipalMapping",
  "Query",
  "Retrieve",
  "StartDataSourceSyncJob",
  "StopDataSourceSyncJob",
  "SubmitFeedback",
  "TagResource",
  "UntagResource",
  "UpdateAccessControlConfiguration",
  "UpdateDataSource",
  "UpdateExperience",
  "UpdateFeaturedResultsSet",
  "UpdateIndex",
  "UpdateQuerySuggestionsBlockList",
  "UpdateQuerySuggestionsConfig",
  "UpdateThesaurus",
] as const;

export type KendraAction = (typeof kendraActions)[number];

export function kendra(action: KendraAction | "*"): `kendra:${KendraAction | "*"}` {
  return `kendra:${action}` as `kendra:${KendraAction | "*"}`;
}
