export const kinesisvideoActions = [
  "ConnectAsMaster",
  "ConnectAsViewer",
  "CreateSignalingChannel",
  "CreateStream",
  "DeleteEdgeConfiguration",
  "DeleteSignalingChannel",
  "DeleteStream",
  "DescribeEdgeConfiguration",
  "DescribeImageGenerationConfiguration",
  "DescribeMappedResourceConfiguration",
  "DescribeMediaStorageConfiguration",
  "DescribeNotificationConfiguration",
  "DescribeSignalingChannel",
  "DescribeStream",
  "DescribeStreamStorageConfiguration",
  "GetClip",
  "GetDASHStreamingSessionURL",
  "GetDataEndpoint",
  "GetHLSStreamingSessionURL",
  "GetIceServerConfig",
  "GetImages",
  "GetMedia",
  "GetMediaForFragmentList",
  "GetSignalingChannelEndpoint",
  "JoinStorageSession",
  "JoinStorageSessionAsViewer",
  "ListEdgeAgentConfigurations",
  "ListFragments",
  "ListSignalingChannels",
  "ListStreams",
  "ListTagsForResource",
  "ListTagsForStream",
  "PutMedia",
  "SendAlexaOfferToMaster",
  "StartEdgeConfigurationUpdate",
  "TagResource",
  "TagStream",
  "UntagResource",
  "UntagStream",
  "UpdateDataRetention",
  "UpdateImageGenerationConfiguration",
  "UpdateMediaStorageConfiguration",
  "UpdateNotificationConfiguration",
  "UpdateSignalingChannel",
  "UpdateStream",
  "UpdateStreamStorageConfiguration",
] as const;

export type KinesisvideoAction = (typeof kinesisvideoActions)[number];

export function kinesisvideo(action: KinesisvideoAction | "*"): `kinesisvideo:${KinesisvideoAction | "*"}` {
  return `kinesisvideo:${action}` as `kinesisvideo:${KinesisvideoAction | "*"}`;
}
