export const kinesisActions = [
  "AddTagsToStream",
  "AssociateStreamsWithChannel",
  "CreateChannel",
  "CreateStream",
  "DecreaseStreamRetentionPeriod",
  "DeleteChannel",
  "DeleteResourcePolicy",
  "DeleteStream",
  "DeregisterStreamConsumer",
  "DescribeAccountSettings",
  "DescribeChannel",
  "DescribeLimits",
  "DescribeStream",
  "DescribeStreamConsumer",
  "DescribeStreamSummary",
  "DisableEnhancedMonitoring",
  "EnableEnhancedMonitoring",
  "GetRecords",
  "GetResourcePolicy",
  "GetShardIterator",
  "IncreaseStreamRetentionPeriod",
  "InjectApiError",
  "ListChannels",
  "ListShards",
  "ListStreamConsumers",
  "ListStreams",
  "ListTagsForResource",
  "ListTagsForStream",
  "MergeShards",
  "PutRecord",
  "PutRecords",
  "PutResourcePolicy",
  "RegisterStreamConsumer",
  "RemoveTagsFromStream",
  "SplitShard",
  "StartStreamEncryption",
  "StopStreamEncryption",
  "SubscribeToShard",
  "TagResource",
  "UntagResource",
  "UpdateAccountSettings",
  "UpdateChannel",
  "UpdateMaxRecordSize",
  "UpdateShardCount",
  "UpdateStreamMode",
  "UpdateStreamWarmThroughput",
] as const;

export type KinesisAction = (typeof kinesisActions)[number];

export function kinesis(action: KinesisAction | "*"): `kinesis:${KinesisAction | "*"}` {
  return `kinesis:${action}` as `kinesis:${KinesisAction | "*"}`;
}
