export const kmsActions = [
  "CancelKeyDeletion",
  "ConnectCustomKeyStore",
  "CreateAlias",
  "CreateCustomKeyStore",
  "CreateGrant",
  "CreateKey",
  "Decrypt",
  "DeleteAlias",
  "DeleteCustomKeyStore",
  "DeleteImportedKeyMaterial",
  "DeriveSharedSecret",
  "DescribeCustomKeyStores",
  "DescribeKey",
  "DisableKey",
  "DisableKeyRotation",
  "DisconnectCustomKeyStore",
  "EnableKey",
  "EnableKeyRotation",
  "Encrypt",
  "GenerateDataKey",
  "GenerateDataKeyPair",
  "GenerateDataKeyPairWithoutPlaintext",
  "GenerateDataKeyWithoutPlaintext",
  "GenerateMac",
  "GenerateRandom",
  "GetKeyLastUsage",
  "GetKeyPolicy",
  "GetKeyRotationStatus",
  "GetParametersForImport",
  "GetPublicKey",
  "ImportKeyMaterial",
  "ListAliases",
  "ListGrants",
  "ListKeyPolicies",
  "ListKeyRotations",
  "ListKeys",
  "ListResourceTags",
  "ListRetirableGrants",
  "PutKeyPolicy",
  "ReEncryptFrom",
  "ReEncryptTo",
  "ReplicateKey",
  "RetireGrant",
  "RevokeGrant",
  "RotateKeyOnDemand",
  "ScheduleKeyDeletion",
  "Sign",
  "SynchronizeMultiRegionKey",
  "TagResource",
  "UntagResource",
  "UpdateAlias",
  "UpdateCustomKeyStore",
  "UpdateKeyDescription",
  "UpdatePrimaryRegion",
  "Verify",
  "VerifyMac",
] as const;

export type KmsAction = (typeof kmsActions)[number];

export function kms(action: KmsAction | "*"): `kms:${KmsAction | "*"}` {
  return `kms:${action}` as `kms:${KmsAction | "*"}`;
}
