export const lakeformationActions = [
  "AddLFTagsToResource",
  "BatchGrantPermissions",
  "BatchRevokePermissions",
  "CancelTransaction",
  "CommitTransaction",
  "CreateDataCellsFilter",
  "CreateLakeFormationIdentityCenterConfiguration",
  "CreateLakeFormationOptIn",
  "CreateLFTag",
  "CreateLFTagExpression",
  "DeleteDataCellsFilter",
  "DeleteLakeFormationIdentityCenterConfiguration",
  "DeleteLakeFormationOptIn",
  "DeleteLFTag",
  "DeleteLFTagExpression",
  "DeleteObjectsOnCancel",
  "DeregisterResource",
  "DescribeLakeFormationIdentityCenterConfiguration",
  "DescribeResource",
  "DescribeTransaction",
  "ExtendTransaction",
  "GetDataAccess",
  "GetDataCellsFilter",
  "GetDataLakePrincipal",
  "GetDataLakeSettings",
  "GetEffectivePermissionsForPath",
  "GetLFTag",
  "GetLFTagExpression",
  "GetQueryState",
  "GetQueryStatistics",
  "GetResourceLFTags",
  "GetTableObjects",
  "GetTemporaryGluePartitionCredentials",
  "GetTemporaryGlueTableCredentials",
  "GetWorkUnitResults",
  "GetWorkUnits",
  "GrantPermissions",
  "ListDataCellsFilter",
  "ListLakeFormationOptIns",
  "ListLFTagExpressions",
  "ListLFTags",
  "ListPermissions",
  "ListResources",
  "ListTableStorageOptimizers",
  "ListTransactions",
  "PutDataLakeSettings",
  "RegisterResource",
  "RegisterResourceWithPrivilegedAccess",
  "RemoveLFTagsFromResource",
  "RevokePermissions",
  "SearchDatabasesByLFTags",
  "SearchTablesByLFTags",
  "StartQueryPlanning",
  "StartTransaction",
  "UpdateDataCellsFilter",
  "UpdateLakeFormationIdentityCenterConfiguration",
  "UpdateLFTag",
  "UpdateLFTagExpression",
  "UpdateResource",
  "UpdateTableObjects",
  "UpdateTableStorageOptimizer",
] as const;

export type LakeformationAction = (typeof lakeformationActions)[number];

export function lakeformation(action: LakeformationAction | "*"): `lakeformation:${LakeformationAction | "*"}` {
  return `lakeformation:${action}` as `lakeformation:${LakeformationAction | "*"}`;
}
