export const lexActions = [
  "CreateBotVersion",
  "CreateIntentVersion",
  "CreateSlotTypeVersion",
  "DeleteBot",
  "DeleteBotAlias",
  "DeleteBotChannelAssociation",
  "DeleteBotVersion",
  "DeleteIntent",
  "DeleteIntentVersion",
  "DeleteSession",
  "DeleteSlotType",
  "DeleteSlotTypeVersion",
  "DeleteUtterances",
  "GetBot",
  "GetBotAlias",
  "GetBotAliases",
  "GetBotChannelAssociation",
  "GetBotChannelAssociations",
  "GetBots",
  "GetBotVersions",
  "GetBuiltinIntent",
  "GetBuiltinIntents",
  "GetBuiltinSlotTypes",
  "GetExport",
  "GetImport",
  "GetIntent",
  "GetIntents",
  "GetIntentVersions",
  "GetMigration",
  "GetMigrations",
  "GetSession",
  "GetSlotType",
  "GetSlotTypes",
  "GetSlotTypeVersions",
  "GetUtterancesView",
  "ListTagsForResource",
  "PostContent",
  "PostText",
  "PutBot",
  "PutBotAlias",
  "PutIntent",
  "PutSession",
  "PutSlotType",
  "StartImport",
  "StartMigration",
  "TagResource",
  "UntagResource",
] as const;

export type LexAction = (typeof lexActions)[number];

export function lex(action: LexAction | "*"): `lex:${LexAction | "*"}` {
  return `lex:${action}` as `lex:${LexAction | "*"}`;
}
