export const licenseManagerActions = [
  "AcceptGrant",
  "CheckInLicense",
  "CheckoutBorrowLicense",
  "CheckoutLicense",
  "CreateGrant",
  "CreateGrantVersion",
  "CreateLicense",
  "CreateLicenseAssetGroup",
  "CreateLicenseAssetRuleset",
  "CreateLicenseConfiguration",
  "CreateLicenseConversionTaskForResource",
  "CreateLicenseManagerReportGenerator",
  "CreateLicenseVersion",
  "CreateToken",
  "DeleteGrant",
  "DeleteLicense",
  "DeleteLicenseAssetGroup",
  "DeleteLicenseAssetRuleset",
  "DeleteLicenseConfiguration",
  "DeleteLicenseManagerReportGenerator",
  "DeleteToken",
  "ExtendLicenseConsumption",
  "GetAccessToken",
  "GetGrant",
  "GetLicense",
  "GetLicenseAssetGroup",
  "GetLicenseAssetRuleset",
  "GetLicenseConfiguration",
  "GetLicenseConversionTask",
  "GetLicenseManagerReportGenerator",
  "GetLicenseUsage",
  "GetServiceSettings",
  "ListAssetsForLicenseAssetGroup",
  "ListAssociationsForLicenseConfiguration",
  "ListDistributedGrants",
  "ListFailuresForLicenseConfigurationOperations",
  "ListLicenseAssetGroups",
  "ListLicenseAssetRulesets",
  "ListLicenseConfigurations",
  "ListLicenseConfigurationsForOrganization",
  "ListLicenseConversionTasks",
  "ListLicenseManagerReportGenerators",
  "ListLicenses",
  "ListLicenseSpecificationsForResource",
  "ListLicenseVersions",
  "ListReceivedGrants",
  "ListReceivedGrantsForOrganization",
  "ListReceivedLicenses",
  "ListReceivedLicensesForOrganization",
  "ListResourceInventory",
  "ListTagsForResource",
  "ListTokens",
  "ListUsageForLicenseConfiguration",
  "RejectGrant",
  "TagResource",
  "UntagResource",
  "UpdateLicenseAssetGroup",
  "UpdateLicenseAssetRuleset",
  "UpdateLicenseConfiguration",
  "UpdateLicenseManagerReportGenerator",
  "UpdateLicenseSpecificationsForResource",
  "UpdateServiceSettings",
] as const;

export type LicenseManagerAction = (typeof licenseManagerActions)[number];

export function licenseManager(action: LicenseManagerAction | "*"): `license-manager:${LicenseManagerAction | "*"}` {
  return `license-manager:${action}` as `license-manager:${LicenseManagerAction | "*"}`;
}
