export const lookoutequipmentActions = [
  "CreateDataset",
  "CreateInferenceScheduler",
  "CreateLabel",
  "CreateLabelGroup",
  "CreateModel",
  "CreateRetrainingScheduler",
  "DeleteDataset",
  "DeleteInferenceScheduler",
  "DeleteLabel",
  "DeleteLabelGroup",
  "DeleteModel",
  "DeleteResourcePolicy",
  "DeleteRetrainingScheduler",
  "DescribeDataIngestionJob",
  "DescribeDataset",
  "DescribeInferenceScheduler",
  "Describelabel",
  "DescribeLabelGroup",
  "DescribeModel",
  "DescribeModelVersion",
  "DescribeResourcePolicy",
  "DescribeRetrainingScheduler",
  "ImportDataset",
  "ImportModelVersion",
  "ListDataIngestionJobs",
  "ListDatasets",
  "ListInferenceEvents",
  "ListInferenceExecutions",
  "ListInferenceSchedulers",
  "ListLabelGroups",
  "ListLabels",
  "ListModels",
  "ListModelVersions",
  "ListRetrainingSchedulers",
  "ListSensorStatistics",
  "ListTagsForResource",
  "PutResourcePolicy",
  "StartDataIngestionJob",
  "StartInferenceScheduler",
  "StartRetrainingScheduler",
  "StopInferenceScheduler",
  "StopRetrainingScheduler",
  "TagResource",
  "UntagResource",
  "UpdateActiveModelVersion",
  "UpdateInferenceScheduler",
  "UpdateLabelGroup",
  "UpdateModel",
  "UpdateRetrainingScheduler",
] as const;

export type LookoutequipmentAction = (typeof lookoutequipmentActions)[number];

export function lookoutequipment(action: LookoutequipmentAction | "*"): `lookoutequipment:${LookoutequipmentAction | "*"}` {
  return `lookoutequipment:${action}` as `lookoutequipment:${LookoutequipmentAction | "*"}`;
}
