export const mediatailorActions = [
  "ConfigureLogsForChannel",
  "ConfigureLogsForPlaybackConfiguration",
  "CreateChannel",
  "CreateLiveSource",
  "CreatePrefetchSchedule",
  "CreateProgram",
  "CreateSourceLocation",
  "CreateVodSource",
  "DeleteChannel",
  "DeleteChannelPolicy",
  "DeleteLiveSource",
  "DeletePlaybackConfiguration",
  "DeletePrefetchSchedule",
  "DeleteProgram",
  "DeleteSourceLocation",
  "DeleteVodSource",
  "DescribeChannel",
  "DescribeLiveSource",
  "DescribeProgram",
  "DescribeSourceLocation",
  "DescribeVodSource",
  "GetChannelPolicy",
  "GetChannelSchedule",
  "GetPlaybackConfiguration",
  "GetPrefetchSchedule",
  "ListAlerts",
  "ListChannels",
  "ListLiveSources",
  "ListPlaybackConfigurations",
  "ListPrefetchSchedules",
  "ListSourceLocations",
  "ListTagsForResource",
  "ListVodSources",
  "PutChannelPolicy",
  "PutPlaybackConfiguration",
  "StartChannel",
  "StopChannel",
  "TagResource",
  "UntagResource",
  "UpdateChannel",
  "UpdateLiveSource",
  "UpdateProgram",
  "UpdateSourceLocation",
  "UpdateVodSource",
] as const;

export type MediatailorAction = (typeof mediatailorActions)[number];

export function mediatailor(action: MediatailorAction | "*"): `mediatailor:${MediatailorAction | "*"}` {
  return `mediatailor:${action}` as `mediatailor:${MediatailorAction | "*"}`;
}
