export const memorydbActions = [
  "BatchUpdateCluster",
  "Connect",
  "CopySnapshot",
  "CreateAcl",
  "CreateCluster",
  "CreateMultiRegionCluster",
  "CreateParameterGroup",
  "CreateSnapshot",
  "CreateSubnetGroup",
  "CreateUser",
  "DeleteAcl",
  "DeleteCluster",
  "DeleteMultiRegionCluster",
  "DeleteParameterGroup",
  "DeleteSnapshot",
  "DeleteSubnetGroup",
  "DeleteUser",
  "DescribeAcls",
  "DescribeClusters",
  "DescribeEngineVersions",
  "DescribeEvents",
  "DescribeMultiRegionClusters",
  "DescribeMultiRegionParameterGroups",
  "DescribeMultiRegionParameters",
  "DescribeParameterGroups",
  "DescribeParameters",
  "DescribeReservedNodes",
  "DescribeReservedNodesOfferings",
  "DescribeServiceUpdates",
  "DescribeSnapshots",
  "DescribeSubnetGroups",
  "DescribeUsers",
  "FailoverShard",
  "ListAllowedMultiRegionClusterUpdates",
  "ListAllowedNodeTypeUpdates",
  "ListTags",
  "PauseMultiRegionClusterReplication",
  "PurchaseReservedNodesOffering",
  "ResetParameterGroup",
  "TagResource",
  "UntagResource",
  "UpdateAcl",
  "UpdateCluster",
  "UpdateMultiRegionCluster",
  "UpdateParameterGroup",
  "UpdateSubnetGroup",
  "UpdateUser",
] as const;

export type MemorydbAction = (typeof memorydbActions)[number];

export function memorydb(action: MemorydbAction | "*"): `memorydb:${MemorydbAction | "*"}` {
  return `memorydb:${action}` as `memorydb:${MemorydbAction | "*"}`;
}
