export const mghActions = [
  "AcceptConnection",
  "AssociateAutomationUnitRole",
  "AssociateCreatedArtifact",
  "AssociateDiscoveredResource",
  "AssociateSourceResource",
  "BatchAssociateIamRoleWithConnection",
  "BatchDisassociateIamRoleFromConnection",
  "CreateAutomationRun",
  "CreateAutomationUnit",
  "CreateHomeRegionControl",
  "CreateProgressUpdateStream",
  "DeleteAutomationRun",
  "DeleteAutomationUnit",
  "DeleteConnection",
  "DeleteHomeRegionControl",
  "DeleteProgressUpdateStream",
  "DescribeApplicationState",
  "DescribeAutomationRun",
  "DescribeAutomationUnit",
  "DescribeHomeRegionControls",
  "DescribeMigrationTask",
  "DisassociateAutomationUnitRole",
  "DisassociateCreatedArtifact",
  "DisassociateDiscoveredResource",
  "DisassociateSourceResource",
  "GetConnection",
  "GetHomeRegion",
  "ImportMigrationTask",
  "ListApplicationStates",
  "ListAutomationRuns",
  "ListAutomationUnits",
  "ListConnectionRoles",
  "ListConnections",
  "ListCreatedArtifacts",
  "ListDiscoveredResources",
  "ListMigrationTasks",
  "ListMigrationTaskUpdates",
  "ListProgressUpdateStreams",
  "ListSourceResources",
  "ListTagsForResource",
  "NotifyApplicationState",
  "NotifyMigrationTaskState",
  "PutResourceAttributes",
  "RejectConnection",
  "TagResource",
  "UntagResource",
] as const;

export type MghAction = (typeof mghActions)[number];

export function mgh(action: MghAction | "*"): `mgh:${MghAction | "*"}` {
  return `mgh:${action}` as `mgh:${MghAction | "*"}`;
}
