export const networkSecurityManagerActions = [
  "CreateDeployment",
  "CreateDeploymentSnapshot",
  "CreatePolicy",
  "CreatePolicySnapshot",
  "CreateRule",
  "CreateRuleSnapshot",
  "CreateScope",
  "CreateScopeSnapshot",
  "CreateTemplate",
  "CreateTemplateSnapshot",
  "DeleteAdminAccount",
  "DeleteDeployment",
  "DeletePolicy",
  "DeleteRule",
  "DeleteScope",
  "DeleteTemplate",
  "GenerateRuleConfiguration",
  "GetAdminAccount",
  "GetDeployment",
  "GetPolicy",
  "GetRule",
  "GetScope",
  "GetTemplate",
  "ListAdminAccounts",
  "ListAggregateResourceSynchronizationStatuses",
  "ListDeployments",
  "ListDeploymentSnapshots",
  "ListPolicies",
  "ListPolicySnapshots",
  "ListResourceAssociations",
  "ListResourceSynchronizationStatuses",
  "ListRules",
  "ListRuleSnapshots",
  "ListScopes",
  "ListScopeSnapshots",
  "ListTagsForResource",
  "ListTemplates",
  "ListTemplateSnapshots",
  "PutAdminAccount",
  "TagResource",
  "UntagResource",
  "UpdateDeployment",
  "UpdatePolicy",
  "UpdateRule",
  "UpdateScope",
  "UpdateTemplate",
] as const;

export type NetworkSecurityManagerAction = (typeof networkSecurityManagerActions)[number];

export function networkSecurityManager(action: NetworkSecurityManagerAction | "*"): `network-security-manager:${NetworkSecurityManagerAction | "*"}` {
  return `network-security-manager:${action}` as `network-security-manager:${NetworkSecurityManagerAction | "*"}`;
}
