export const nimbleActions = [
  "AcceptEulas",
  "CreateLaunchProfile",
  "CreateStreamingImage",
  "CreateStreamingSession",
  "CreateStreamingSessionStream",
  "CreateStudio",
  "CreateStudioComponent",
  "DeleteLaunchProfile",
  "DeleteLaunchProfileMember",
  "DeleteStreamingImage",
  "DeleteStreamingSession",
  "DeleteStudio",
  "DeleteStudioComponent",
  "DeleteStudioMember",
  "GetEula",
  "GetFeatureMap",
  "GetLaunchProfile",
  "GetLaunchProfileDetails",
  "GetLaunchProfileInitialization",
  "GetLaunchProfileMember",
  "GetStreamingImage",
  "GetStreamingSession",
  "GetStreamingSessionBackup",
  "GetStreamingSessionStream",
  "GetStudio",
  "GetStudioComponent",
  "GetStudioMember",
  "ListEulaAcceptances",
  "ListEulas",
  "ListLaunchProfileMembers",
  "ListLaunchProfiles",
  "ListStreamingImages",
  "ListStreamingSessionBackups",
  "ListStreamingSessions",
  "ListStudioComponents",
  "ListStudioMembers",
  "ListStudios",
  "ListTagsForResource",
  "PutLaunchProfileMembers",
  "PutStudioLogEvents",
  "PutStudioMembers",
  "StartStreamingSession",
  "StartStudioSSOConfigurationRepair",
  "StopStreamingSession",
  "TagResource",
  "UntagResource",
  "UpdateLaunchProfile",
  "UpdateLaunchProfileMember",
  "UpdateStreamingImage",
  "UpdateStudio",
  "UpdateStudioComponent",
] as const;

export type NimbleAction = (typeof nimbleActions)[number];

export function nimble(action: NimbleAction | "*"): `nimble:${NimbleAction | "*"}` {
  return `nimble:${action}` as `nimble:${NimbleAction | "*"}`;
}
