export const notificationsActions = [
  "AssociateChannel",
  "AssociateManagedNotificationAccountContact",
  "AssociateManagedNotificationAdditionalChannel",
  "AssociateOrganizationalUnit",
  "CreateEventRule",
  "CreateNotificationConfiguration",
  "DeleteEventRule",
  "DeleteNotificationConfiguration",
  "DeregisterNotificationHub",
  "DisableNotificationsAccessForOrganization",
  "DisassociateChannel",
  "DisassociateManagedNotificationAccountContact",
  "DisassociateManagedNotificationAdditionalChannel",
  "DisassociateOrganizationalUnit",
  "EnableNotificationsAccessForOrganization",
  "GetEventRule",
  "GetFeatureOptInStatus",
  "GetManagedNotificationChildEvent",
  "GetManagedNotificationConfiguration",
  "GetManagedNotificationEvent",
  "GetNotificationConfiguration",
  "GetNotificationEvent",
  "GetNotificationsAccessForOrganization",
  "ListChannels",
  "ListEventRules",
  "ListManagedNotificationChannelAssociations",
  "ListManagedNotificationChildEvents",
  "ListManagedNotificationConfigurations",
  "ListManagedNotificationEvents",
  "ListMemberAccounts",
  "ListNotificationConfigurations",
  "ListNotificationEvents",
  "ListNotificationHubs",
  "ListOrganizationalUnits",
  "ListTagsForResource",
  "PutFeatureOptInStatus",
  "RegisterNotificationHub",
  "TagResource",
  "UntagResource",
  "UpdateEventRule",
  "UpdateNotificationConfiguration",
] as const;

export type NotificationsAction = (typeof notificationsActions)[number];

export function notifications(action: NotificationsAction | "*"): `notifications:${NotificationsAction | "*"}` {
  return `notifications:${action}` as `notifications:${NotificationsAction | "*"}`;
}
