export const odbActions = [
  "AcceptMarketplaceRegistration",
  "AssociateIamRoleToResource",
  "CreateCloudAutonomousVmCluster",
  "CreateCloudExadataInfrastructure",
  "CreateCloudVmCluster",
  "CreateDbNode",
  "CreateGrantShare",
  "CreateOdbNetwork",
  "CreateOdbPeeringConnection",
  "CreateOutboundIntegration",
  "DeleteCloudAutonomousVmCluster",
  "DeleteCloudExadataInfrastructure",
  "DeleteCloudVmCluster",
  "DeleteDbNode",
  "DeleteGrantShare",
  "DeleteOdbNetwork",
  "DeleteOdbPeeringConnection",
  "DeleteResourcePolicy",
  "DisassociateIamRoleFromResource",
  "GetCloudAutonomousVmCluster",
  "GetCloudExadataInfrastructure",
  "GetCloudExadataInfrastructureUnallocatedResources",
  "GetCloudVmCluster",
  "GetDbNode",
  "GetDbServer",
  "GetOciOnboardingStatus",
  "GetOdbNetwork",
  "GetOdbPeeringConnection",
  "GetResourcePolicy",
  "InitializeService",
  "ListAutonomousVirtualMachines",
  "ListCloudAutonomousVmClusters",
  "ListCloudExadataInfrastructures",
  "ListCloudVmClusters",
  "ListDbNodes",
  "ListDbServers",
  "ListDbSystemShapes",
  "ListGiVersions",
  "ListOdbNetworks",
  "ListOdbPeeringConnections",
  "ListSystemVersions",
  "ListTagsForResource",
  "PutResourcePolicy",
  "RebootDbNode",
  "StartDbNode",
  "StopDbNode",
  "TagResource",
  "UntagResource",
  "UpdateCloudExadataInfrastructure",
  "UpdateGrantShare",
  "UpdateOdbNetwork",
  "UpdateOdbPeeringConnection",
  "UpdateOutboundIntegration",
] as const;

export type OdbAction = (typeof odbActions)[number];

export function odb(action: OdbAction | "*"): `odb:${OdbAction | "*"}` {
  return `odb:${action}` as `odb:${OdbAction | "*"}`;
}
