export const organizationsActions = [
  "AcceptHandshake",
  "AttachPolicy",
  "CancelHandshake",
  "CloseAccount",
  "CreateAccount",
  "CreateGovCloudAccount",
  "CreateOrganization",
  "CreateOrganizationalUnit",
  "CreatePolicy",
  "DeclineHandshake",
  "DeleteOrganization",
  "DeleteOrganizationalUnit",
  "DeletePolicy",
  "DeleteResourcePolicy",
  "DeregisterDelegatedAdministrator",
  "DescribeAccount",
  "DescribeCreateAccountStatus",
  "DescribeEffectivePolicy",
  "DescribeHandshake",
  "DescribeOrganization",
  "DescribeOrganizationalUnit",
  "DescribePolicy",
  "DescribeResourcePolicy",
  "DescribeResponsibilityTransfer",
  "DetachPolicy",
  "DisableAWSServiceAccess",
  "DisablePolicyType",
  "EnableAllFeatures",
  "EnableAWSServiceAccess",
  "EnablePolicyType",
  "InviteAccountToOrganization",
  "InviteOrganizationToTransferResponsibility",
  "LeaveOrganization",
  "ListAccounts",
  "ListAccountsForParent",
  "ListAccountsWithInvalidEffectivePolicy",
  "ListAWSServiceAccessForOrganization",
  "ListChildren",
  "ListCreateAccountStatus",
  "ListDelegatedAdministrators",
  "ListDelegatedServicesForAccount",
  "ListEffectivePolicyValidationErrors",
  "ListHandshakesForAccount",
  "ListHandshakesForOrganization",
  "ListInboundResponsibilityTransfers",
  "ListOrganizationalUnitsForParent",
  "ListOutboundResponsibilityTransfers",
  "ListParents",
  "ListPolicies",
  "ListPoliciesForTarget",
  "ListRoots",
  "ListTagsForResource",
  "ListTargetsForPolicy",
  "MoveAccount",
  "PutResourcePolicy",
  "RegisterDelegatedAdministrator",
  "RemoveAccountFromOrganization",
  "TagResource",
  "TerminateResponsibilityTransfer",
  "UntagResource",
  "UpdateOrganizationalUnit",
  "UpdatePolicy",
  "UpdateResponsibilityTransfer",
] as const;

export type OrganizationsAction = (typeof organizationsActions)[number];

export function organizations(action: OrganizationsAction | "*"): `organizations:${OrganizationsAction | "*"}` {
  return `organizations:${action}` as `organizations:${OrganizationsAction | "*"}`;
}
