export const outpostsActions = [
  "CancelCapacityTask",
  "CancelOrder",
  "CreateOrder",
  "CreateOutpost",
  "CreatePrivateConnectivityConfig",
  "CreateQuote",
  "CreateRenewal",
  "CreateSite",
  "DeleteOutpost",
  "DeleteQuote",
  "DeleteSite",
  "GetCapacityTask",
  "GetCatalogItem",
  "GetConnection",
  "GetOrder",
  "GetOutpost",
  "GetOutpostBillingInformation",
  "GetOutpostInstanceTypes",
  "GetOutpostSupportedInstanceTypes",
  "GetPrivateConnectivityConfig",
  "GetQuote",
  "GetRenewalPricing",
  "GetSite",
  "GetSiteAddress",
  "ListAssetInstances",
  "ListAssets",
  "ListBlockingInstancesForCapacityTask",
  "ListCapacityTasks",
  "ListCatalogItems",
  "ListOrderableInstanceTypes",
  "ListOrders",
  "ListOutposts",
  "ListQuotes",
  "ListSites",
  "ListTagsForResource",
  "StartCapacityTask",
  "StartConnection",
  "TagResource",
  "UntagResource",
  "UpdateOutpost",
  "UpdateQuote",
  "UpdateSite",
  "UpdateSiteAddress",
  "UpdateSiteRackPhysicalProperties",
] as const;

export type OutpostsAction = (typeof outpostsActions)[number];

export function outposts(action: OutpostsAction | "*"): `outposts:${OutpostsAction | "*"}` {
  return `outposts:${action}` as `outposts:${OutpostsAction | "*"}`;
}
