export const paymentCryptographyActions = [
  "AddKeyReplicationRegions",
  "AssociateMpaTeam",
  "CreateAlias",
  "CreateKey",
  "DecryptData",
  "DeleteAlias",
  "DeleteKey",
  "DeleteResourcePolicy",
  "DisableDefaultKeyReplicationRegions",
  "DisassociateMpaTeam",
  "EnableDefaultKeyReplicationRegions",
  "EncryptData",
  "ExportKey",
  "GenerateAs2805KekValidation",
  "GenerateAuthRequestCryptogram",
  "GenerateCardValidationData",
  "GenerateMac",
  "GenerateMacEmvPinChange",
  "GeneratePinData",
  "GetAlias",
  "GetCertificateSigningRequest",
  "GetDefaultKeyReplicationRegions",
  "GetKey",
  "GetMpaTeamAssociation",
  "GetParametersForExport",
  "GetParametersForImport",
  "GetPublicKeyCertificate",
  "GetResourcePolicy",
  "ImportKey",
  "ListAliases",
  "ListKeys",
  "ListTagsForResource",
  "PutResourcePolicy",
  "ReEncryptData",
  "RemoveKeyReplicationRegions",
  "RestoreKey",
  "StartKeyUsage",
  "StopKeyUsage",
  "TagResource",
  "TranslateKeyMaterial",
  "TranslatePinData",
  "UntagResource",
  "UpdateAlias",
  "VerifyAuthRequestCryptogram",
  "VerifyCardValidationData",
  "VerifyMac",
  "VerifyPinData",
] as const;

export type PaymentCryptographyAction = (typeof paymentCryptographyActions)[number];

export function paymentCryptography(action: PaymentCryptographyAction | "*"): `payment-cryptography:${PaymentCryptographyAction | "*"}` {
  return `payment-cryptography:${action}` as `payment-cryptography:${PaymentCryptographyAction | "*"}`;
}
