export const qActions = [
  "AssociateConnectorResource",
  "AssociateLoginDomain",
  "BatchDescribeGroups",
  "BatchDescribeUsers",
  "BatchGetGroups",
  "BatchGetUsers",
  "CreateArtifact",
  "CreateAssignment",
  "CreateAuthGrant",
  "CreateOAuthAppConnection",
  "CreatePlugin",
  "CreateScimAccessToken",
  "DeleteAssignment",
  "DeleteConversation",
  "DeleteOAuthAppConnection",
  "DeletePlugin",
  "DeleteScimAccessToken",
  "DisassociateLoginDomain",
  "GenerateCodeFromCommands",
  "GenerateCodeRecommendations",
  "GetArtifact",
  "GetArtifactActionResult",
  "GetConnector",
  "GetConversation",
  "GetIdentityMetadata",
  "GetPlugin",
  "GetTroubleshootingResults",
  "ListConversations",
  "ListDashboardMetrics",
  "ListGroups",
  "ListLoginDomains",
  "ListPluginProviders",
  "ListPlugins",
  "ListScimAccessTokens",
  "ListTagsForResource",
  "ListUsers",
  "PassRequest",
  "PerformArtifactAction",
  "RejectConnector",
  "SendEvent",
  "SendMessage",
  "StartConversation",
  "StartTroubleshootingAnalysis",
  "StartTroubleshootingResolutionExplanation",
  "TagResource",
  "UntagResource",
  "UpdateAssignment",
  "UpdateAuthGrant",
  "UpdateConversation",
  "UpdateOAuthAppConnection",
  "UpdatePlugin",
  "UpdateTroubleshootingCommandResult",
  "UsePlugin",
  "VerifyOAuthAppConnection",
] as const;

export type QAction = (typeof qActions)[number];

export function q(action: QAction | "*"): `q:${QAction | "*"}` {
  return `q:${action}` as `q:${QAction | "*"}`;
}
