export const redshiftServerlessActions = [
  "ConvertRecoveryPointToSnapshot",
  "CreateCustomDomainAssociation",
  "CreateEndpointAccess",
  "CreateNamespace",
  "CreateReservation",
  "CreateScheduledAction",
  "CreateSnapshot",
  "CreateSnapshotCopyConfiguration",
  "CreateUsageLimit",
  "CreateWorkgroup",
  "DeleteCustomDomainAssociation",
  "DeleteEndpointAccess",
  "DeleteNamespace",
  "DeleteResourcePolicy",
  "DeleteScheduledAction",
  "DeleteSnapshot",
  "DeleteSnapshotCopyConfiguration",
  "DeleteUsageLimit",
  "DeleteWorkgroup",
  "DescribeOneTimeCredit",
  "GetCredentials",
  "GetCustomDomainAssociation",
  "GetEndpointAccess",
  "GetIdentityCenterAuthToken",
  "GetManagedWorkgroup",
  "GetNamespace",
  "GetRecoveryPoint",
  "GetReservation",
  "GetReservationOffering",
  "GetResourcePolicy",
  "GetScheduledAction",
  "GetSnapshot",
  "GetTableRestoreStatus",
  "GetTrack",
  "GetUsageLimit",
  "GetWorkgroup",
  "ListAutonomicsDenylist",
  "ListCustomDomainAssociations",
  "ListEndpointAccess",
  "ListManagedWorkgroups",
  "ListNamespaces",
  "ListRecoveryPoints",
  "ListReservationOfferings",
  "ListReservations",
  "ListScheduledActions",
  "ListSnapshotCopyConfigurations",
  "ListSnapshots",
  "ListTableRestoreStatus",
  "ListTagsForResource",
  "ListTracks",
  "ListUsageLimits",
  "ListWorkgroups",
  "PutResourcePolicy",
  "RestoreFromRecoveryPoint",
  "RestoreFromSnapshot",
  "RestoreTableFromRecoveryPoint",
  "RestoreTableFromSnapshot",
  "TagResource",
  "UntagResource",
  "UpdateAutonomicsDenylist",
  "UpdateCustomDomainAssociation",
  "UpdateEndpointAccess",
  "UpdateNamespace",
  "UpdateScheduledAction",
  "UpdateSnapshot",
  "UpdateSnapshotCopyConfiguration",
  "UpdateUsageLimit",
  "UpdateWorkgroup",
] as const;

export type RedshiftServerlessAction = (typeof redshiftServerlessActions)[number];

export function redshiftServerless(action: RedshiftServerlessAction | "*"): `redshift-serverless:${RedshiftServerlessAction | "*"}` {
  return `redshift-serverless:${action}` as `redshift-serverless:${RedshiftServerlessAction | "*"}`;
}
