export const resiliencehubActions = [
  "AcceptResourceGroupingRecommendations",
  "AddDraftAppVersionResourceMappings",
  "BatchUpdateRecommendationStatus",
  "CreateApp",
  "CreateAppVersionAppComponent",
  "CreateAppVersionResource",
  "CreateRecommendationTemplate",
  "CreateResiliencyPolicy",
  "DeleteApp",
  "DeleteAppAssessment",
  "DeleteAppInputSource",
  "DeleteAppVersionAppComponent",
  "DeleteAppVersionResource",
  "DeleteRecommendationTemplate",
  "DeleteResiliencyPolicy",
  "DescribeApp",
  "DescribeAppAssessment",
  "DescribeAppVersion",
  "DescribeAppVersionAppComponent",
  "DescribeAppVersionResource",
  "DescribeAppVersionResourcesResolutionStatus",
  "DescribeAppVersionTemplate",
  "DescribeDraftAppVersionResourcesImportStatus",
  "DescribeMetricsExport",
  "DescribeResiliencyPolicy",
  "DescribeResourceGroupingRecommendationTask",
  "ImportResourcesToDraftAppVersion",
  "ListAlarmRecommendations",
  "ListAppAssessmentComplianceDrifts",
  "ListAppAssessmentResourceDrifts",
  "ListAppAssessments",
  "ListAppComponentCompliances",
  "ListAppComponentRecommendations",
  "ListAppInputSources",
  "ListApps",
  "ListAppVersionAppComponents",
  "ListAppVersionResourceMappings",
  "ListAppVersionResources",
  "ListAppVersions",
  "ListMetrics",
  "ListRecommendationTemplates",
  "ListResiliencyPolicies",
  "ListResourceGroupingRecommendations",
  "ListSopRecommendations",
  "ListSuggestedResiliencyPolicies",
  "ListTagsForResource",
  "ListTestRecommendations",
  "ListUnsupportedAppVersionResources",
  "PublishAppVersion",
  "PutDraftAppVersionTemplate",
  "RejectResourceGroupingRecommendations",
  "RemoveDraftAppVersionResourceMappings",
  "ResolveAppVersionResources",
  "StartAppAssessment",
  "StartMetricsExport",
  "StartResourceGroupingRecommendationTask",
  "TagResource",
  "UntagResource",
  "UpdateApp",
  "UpdateAppVersion",
  "UpdateAppVersionAppComponent",
  "UpdateAppVersionResource",
  "UpdateResiliencyPolicy",
] as const;

export type ResiliencehubAction = (typeof resiliencehubActions)[number];

export function resiliencehub(action: ResiliencehubAction | "*"): `resiliencehub:${ResiliencehubAction | "*"}` {
  return `resiliencehub:${action}` as `resiliencehub:${ResiliencehubAction | "*"}`;
}
