export const robomakerActions = [
  "BatchDeleteWorlds",
  "BatchDescribeSimulationJob",
  "CancelDeploymentJob",
  "CancelSimulationJob",
  "CancelSimulationJobBatch",
  "CancelWorldExportJob",
  "CancelWorldGenerationJob",
  "CreateDeploymentJob",
  "CreateFleet",
  "CreateRobot",
  "CreateRobotApplication",
  "CreateRobotApplicationVersion",
  "CreateSimulationApplication",
  "CreateSimulationApplicationVersion",
  "CreateSimulationJob",
  "CreateWorldExportJob",
  "CreateWorldGenerationJob",
  "CreateWorldTemplate",
  "DeleteFleet",
  "DeleteRobot",
  "DeleteRobotApplication",
  "DeleteSimulationApplication",
  "DeleteWorldTemplate",
  "DeregisterRobot",
  "DescribeDeploymentJob",
  "DescribeFleet",
  "DescribeRobot",
  "DescribeRobotApplication",
  "DescribeSimulationApplication",
  "DescribeSimulationJob",
  "DescribeSimulationJobBatch",
  "DescribeWorld",
  "DescribeWorldExportJob",
  "DescribeWorldGenerationJob",
  "DescribeWorldTemplate",
  "GetWorldTemplateBody",
  "ListDeploymentJobs",
  "ListFleets",
  "ListRobotApplications",
  "ListRobots",
  "ListSimulationApplications",
  "ListSimulationJobBatches",
  "ListSimulationJobs",
  "ListSupportedAvailabilityZones",
  "ListTagsForResource",
  "ListWorldExportJobs",
  "ListWorldGenerationJobs",
  "ListWorlds",
  "ListWorldTemplates",
  "RegisterRobot",
  "RestartSimulationJob",
  "StartSimulationJobBatch",
  "SyncDeploymentJob",
  "TagResource",
  "UntagResource",
  "UpdateRobotApplication",
  "UpdateRobotDeployment",
  "UpdateSimulationApplication",
  "UpdateWorldTemplate",
] as const;

export type RobomakerAction = (typeof robomakerActions)[number];

export function robomaker(action: RobomakerAction | "*"): `robomaker:${RobomakerAction | "*"}` {
  return `robomaker:${action}` as `robomaker:${RobomakerAction | "*"}`;
}
