export const route53resolverActions = [
  "AssociateFirewallRuleGroup",
  "AssociateResolverEndpointIpAddress",
  "AssociateResolverQueryLogConfig",
  "AssociateResolverRule",
  "CreateFirewallDomainList",
  "CreateFirewallRule",
  "CreateFirewallRuleGroup",
  "CreateOutpostResolver",
  "CreateResolverEndpoint",
  "CreateResolverQueryLogConfig",
  "CreateResolverRule",
  "DeleteFirewallDomainList",
  "DeleteFirewallRule",
  "DeleteFirewallRuleGroup",
  "DeleteOutpostResolver",
  "DeleteResolverEndpoint",
  "DeleteResolverQueryLogConfig",
  "DeleteResolverRule",
  "DisassociateFirewallRuleGroup",
  "DisassociateResolverEndpointIpAddress",
  "DisassociateResolverQueryLogConfig",
  "DisassociateResolverRule",
  "GetFirewallConfig",
  "GetFirewallDomainList",
  "GetFirewallRuleGroup",
  "GetFirewallRuleGroupAssociation",
  "GetFirewallRuleGroupPolicy",
  "GetOutpostResolver",
  "GetResolverConfig",
  "GetResolverDnssecConfig",
  "GetResolverEndpoint",
  "GetResolverQueryLogConfig",
  "GetResolverQueryLogConfigAssociation",
  "GetResolverQueryLogConfigPolicy",
  "GetResolverRule",
  "GetResolverRuleAssociation",
  "GetResolverRulePolicy",
  "ImportFirewallDomains",
  "ListFirewallConfigs",
  "ListFirewallDomainLists",
  "ListFirewallDomains",
  "ListFirewallRuleGroupAssociations",
  "ListFirewallRuleGroups",
  "ListFirewallRules",
  "ListFirewallRuleTypes",
  "ListOutpostResolvers",
  "ListResolverConfigs",
  "ListResolverDnssecConfigs",
  "ListResolverEndpointIpAddresses",
  "ListResolverEndpoints",
  "ListResolverQueryLogConfigAssociations",
  "ListResolverQueryLogConfigs",
  "ListResolverRuleAssociations",
  "ListResolverRules",
  "ListTagsForResource",
  "PutFirewallRuleGroupPolicy",
  "PutResolverQueryLogConfigPolicy",
  "PutResolverRulePolicy",
  "TagResource",
  "UntagResource",
  "UpdateFirewallConfig",
  "UpdateFirewallDomains",
  "UpdateFirewallRule",
  "UpdateFirewallRuleGroupAssociation",
  "UpdateOutpostResolver",
  "UpdateResolverConfig",
  "UpdateResolverDnssecConfig",
  "UpdateResolverEndpoint",
  "UpdateResolverRule",
] as const;

export type Route53resolverAction = (typeof route53resolverActions)[number];

export function route53resolver(action: Route53resolverAction | "*"): `route53resolver:${Route53resolverAction | "*"}` {
  return `route53resolver:${action}` as `route53resolver:${Route53resolverAction | "*"}`;
}
