export const route53globalresolverActions = [
  "AllowVendedLogDeliveryForResource",
  "AssociateHostedZone",
  "BatchCreateFirewallRule",
  "BatchDeleteFirewallRule",
  "BatchUpdateFirewallRule",
  "CreateAccessSource",
  "CreateAccessToken",
  "CreateDNSView",
  "CreateFirewallDomainList",
  "CreateFirewallRule",
  "CreateGlobalResolver",
  "DeleteAccessSource",
  "DeleteAccessToken",
  "DeleteDNSView",
  "DeleteFirewallDomainList",
  "DeleteFirewallRule",
  "DeleteGlobalResolver",
  "DisableDNSView",
  "DisassociateHostedZone",
  "EnableDNSView",
  "GetAccessSource",
  "GetAccessToken",
  "GetDNSView",
  "GetFirewallDomainList",
  "GetFirewallRule",
  "GetGlobalResolver",
  "GetHostedZoneAssociation",
  "GetManagedFirewallDomainList",
  "ImportFirewallDomains",
  "ListAccessSources",
  "ListAccessTokens",
  "ListDNSViews",
  "ListFirewallDomainLists",
  "ListFirewallDomains",
  "ListFirewallRules",
  "ListGlobalResolvers",
  "ListHostedZoneAssociations",
  "ListManagedFirewallDomainLists",
  "ListTagsForResource",
  "TagResource",
  "UntagResource",
  "UpdateAccessSource",
  "UpdateAccessToken",
  "UpdateDNSView",
  "UpdateFirewallDomains",
  "UpdateFirewallRule",
  "UpdateGlobalResolver",
  "UpdateHostedZoneAssociation",
] as const;

export type Route53globalresolverAction = (typeof route53globalresolverActions)[number];

export function route53globalresolver(action: Route53globalresolverAction | "*"): `route53globalresolver:${Route53globalresolverAction | "*"}` {
  return `route53globalresolver:${action}` as `route53globalresolver:${Route53globalresolverAction | "*"}`;
}
