export const s3OutpostsActions = [
  "AbortMultipartUpload",
  "CreateAccessPoint",
  "CreateBucket",
  "CreateEndpoint",
  "DeleteAccessPoint",
  "DeleteAccessPointPolicy",
  "DeleteBucket",
  "DeleteBucketPolicy",
  "DeleteEndpoint",
  "DeleteObject",
  "DeleteObjectTagging",
  "DeleteObjectVersion",
  "DeleteObjectVersionTagging",
  "GetAccessPoint",
  "GetAccessPointPolicy",
  "GetBucket",
  "GetBucketPolicy",
  "GetBucketTagging",
  "GetBucketVersioning",
  "GetLifecycleConfiguration",
  "GetObject",
  "GetObjectTagging",
  "GetObjectVersion",
  "GetObjectVersionForReplication",
  "GetObjectVersionTagging",
  "GetReplicationConfiguration",
  "ListAccessPoints",
  "ListBucket",
  "ListBucketMultipartUploads",
  "ListBucketVersions",
  "ListEndpoints",
  "ListMultipartUploadParts",
  "ListOutpostsWithS3",
  "ListRegionalBuckets",
  "ListSharedEndpoints",
  "PutAccessPointPolicy",
  "PutBucketPolicy",
  "PutBucketTagging",
  "PutBucketVersioning",
  "PutLifecycleConfiguration",
  "PutObject",
  "PutObjectAcl",
  "PutObjectTagging",
  "PutObjectVersionTagging",
  "PutReplicationConfiguration",
  "ReplicateDelete",
  "ReplicateObject",
  "ReplicateTags",
] as const;

export type S3OutpostsAction = (typeof s3OutpostsActions)[number];

export function s3Outposts(action: S3OutpostsAction | "*"): `s3-outposts:${S3OutpostsAction | "*"}` {
  return `s3-outposts:${action}` as `s3-outposts:${S3OutpostsAction | "*"}`;
}
