export const s3tablesActions = [
  "CreateNamespace",
  "CreateTable",
  "CreateTableBucket",
  "DeleteNamespace",
  "DeleteTable",
  "DeleteTableBucket",
  "DeleteTableBucketEncryption",
  "DeleteTableBucketMetricsConfiguration",
  "DeleteTableBucketPolicy",
  "DeleteTableBucketReplication",
  "DeleteTablePolicy",
  "DeleteTableReplication",
  "GetNamespace",
  "GetTable",
  "GetTableBucket",
  "GetTableBucketEncryption",
  "GetTableBucketMaintenanceConfiguration",
  "GetTableBucketMetricsConfiguration",
  "GetTableBucketPolicy",
  "GetTableBucketReplication",
  "GetTableBucketStorageClass",
  "GetTableData",
  "GetTableEncryption",
  "GetTableMaintenanceConfiguration",
  "GetTableMaintenanceJobStatus",
  "GetTableMetadataLocation",
  "GetTablePolicy",
  "GetTableRecordExpirationConfiguration",
  "GetTableRecordExpirationJobStatus",
  "GetTableReplication",
  "GetTableReplicationStatus",
  "GetTableStorageClass",
  "ListNamespaces",
  "ListTableBuckets",
  "ListTables",
  "ListTagsForResource",
  "PutTableBucketEncryption",
  "PutTableBucketMaintenanceConfiguration",
  "PutTableBucketMetricsConfiguration",
  "PutTableBucketPolicy",
  "PutTableBucketReplication",
  "PutTableBucketStorageClass",
  "PutTableData",
  "PutTableEncryption",
  "PutTableMaintenanceConfiguration",
  "PutTablePolicy",
  "PutTableRecordExpirationConfiguration",
  "PutTableReplication",
  "PutTableStorageClass",
  "RenameTable",
  "TagResource",
  "UntagResource",
  "UpdateTableMetadataLocation",
] as const;

export type S3tablesAction = (typeof s3tablesActions)[number];

export function s3tables(action: S3tablesAction | "*"): `s3tables:${S3tablesAction | "*"}` {
  return `s3tables:${action}` as `s3tables:${S3tablesAction | "*"}`;
}
