export const sagemakerMlflowActions = [
  "AccessUI",
  "CreateExperiment",
  "CreateModelVersion",
  "CreateRegisteredModel",
  "CreateRun",
  "DeleteExperiment",
  "DeleteLoggedModel",
  "DeleteLoggedModelTag",
  "DeleteModelVersion",
  "DeleteModelVersionTag",
  "DeleteRegisteredModel",
  "DeleteRegisteredModelAlias",
  "DeleteRegisteredModelTag",
  "DeleteRun",
  "DeleteTag",
  "DeleteTraces",
  "DeleteTraceTag",
  "EndTrace",
  "FinalizeLoggedModel",
  "GetDownloadURIForModelVersionArtifacts",
  "GetExperiment",
  "GetExperimentByName",
  "GetLatestModelVersions",
  "GetLoggedModel",
  "GetMetricHistory",
  "GetModelVersion",
  "GetModelVersionByAlias",
  "GetRegisteredModel",
  "GetRun",
  "GetTraceInfo",
  "ListArtifacts",
  "ListLoggedModelArtifacts",
  "LogBatch",
  "LogInputs",
  "LogLoggedModelParams",
  "LogMetric",
  "LogModel",
  "LogOutputs",
  "LogParam",
  "RenameRegisteredModel",
  "RestoreExperiment",
  "RestoreRun",
  "SearchExperiments",
  "SearchLoggedModels",
  "SearchModelVersions",
  "SearchRegisteredModels",
  "SearchRuns",
  "SearchTraces",
  "SetExperimentTag",
  "SetLoggedModelTags",
  "SetModelVersionTag",
  "SetRegisteredModelAlias",
  "SetRegisteredModelTag",
  "SetTag",
  "SetTraceTag",
  "StartTrace",
  "TransitionModelVersionStage",
  "UpdateExperiment",
  "UpdateModelVersion",
  "UpdateRegisteredModel",
  "UpdateRun",
] as const;

export type SagemakerMlflowAction = (typeof sagemakerMlflowActions)[number];

export function sagemakerMlflow(action: SagemakerMlflowAction | "*"): `sagemaker-mlflow:${SagemakerMlflowAction | "*"}` {
  return `sagemaker-mlflow:${action}` as `sagemaker-mlflow:${SagemakerMlflowAction | "*"}`;
}
