export const snsActions = [
  "AddPermission",
  "CheckIfPhoneNumberIsOptedOut",
  "ConfirmSubscription",
  "CreatePlatformApplication",
  "CreatePlatformEndpoint",
  "CreateSMSSandboxPhoneNumber",
  "CreateTopic",
  "DeleteEndpoint",
  "DeletePlatformApplication",
  "DeleteSMSSandboxPhoneNumber",
  "DeleteTopic",
  "GetDataProtectionPolicy",
  "GetEndpointAttributes",
  "GetPlatformApplicationAttributes",
  "GetSMSAttributes",
  "GetSMSSandboxAccountStatus",
  "GetSubscriptionAttributes",
  "GetTopicAttributes",
  "ListEndpointsByPlatformApplication",
  "ListOriginationNumbers",
  "ListPhoneNumbersOptedOut",
  "ListPlatformApplications",
  "ListSMSSandboxPhoneNumbers",
  "ListSubscriptions",
  "ListSubscriptionsByTopic",
  "ListTagsForResource",
  "ListTopics",
  "OptInPhoneNumber",
  "Publish",
  "PutDataProtectionPolicy",
  "RemovePermission",
  "SetEndpointAttributes",
  "SetPlatformApplicationAttributes",
  "SetSMSAttributes",
  "SetSubscriptionAttributes",
  "SetTopicAttributes",
  "Subscribe",
  "TagResource",
  "Unsubscribe",
  "UntagResource",
  "VerifySMSSandboxPhoneNumber",
] as const;

export type SnsAction = (typeof snsActions)[number];

export function sns(action: SnsAction | "*"): `sns:${SnsAction | "*"}` {
  return `sns:${action}` as `sns:${SnsAction | "*"}`;
}
