export const socialMessagingActions = [
  "AssociateWhatsAppBusinessAccount",
  "CreateWhatsAppDataset",
  "CreateWhatsAppFlow",
  "CreateWhatsAppMessageTemplate",
  "CreateWhatsAppMessageTemplateFromLibrary",
  "CreateWhatsAppMessageTemplateMedia",
  "DeleteWhatsAppFlow",
  "DeleteWhatsAppMessageMedia",
  "DeleteWhatsAppMessageTemplate",
  "DeprecateWhatsAppFlow",
  "DisassociateWhatsAppBusinessAccount",
  "GetLinkedWhatsAppBusinessAccount",
  "GetLinkedWhatsAppBusinessAccountPhoneNumber",
  "GetWhatsAppBusinessPublicKey",
  "GetWhatsAppCallPermission",
  "GetWhatsAppFlow",
  "GetWhatsAppFlowPreview",
  "GetWhatsAppMessageMedia",
  "GetWhatsAppMessageTemplate",
  "ListLinkedWhatsAppBusinessAccounts",
  "ListTagsForResource",
  "ListWhatsAppFlowAssets",
  "ListWhatsAppFlows",
  "ListWhatsAppMessageTemplates",
  "ListWhatsAppTemplateLibrary",
  "PostWhatsAppMessageMedia",
  "PublishWhatsAppFlow",
  "PutWhatsAppBusinessAccountEventDestinations",
  "PutWhatsAppBusinessPublicKey",
  "SendWhatsAppCallEvent",
  "SendWhatsAppConversionEvent",
  "SendWhatsAppMessage",
  "TagResource",
  "UntagResource",
  "UpdateLinkedWhatsAppBusinessAccountPhoneNumber",
  "UpdateWhatsAppFlow",
  "UpdateWhatsAppFlowAssets",
  "UpdateWhatsAppMessageTemplate",
] as const;

export type SocialMessagingAction = (typeof socialMessagingActions)[number];

export function socialMessaging(action: SocialMessagingAction | "*"): `social-messaging:${SocialMessagingAction | "*"}` {
  return `social-messaging:${action}` as `social-messaging:${SocialMessagingAction | "*"}`;
}
