export const ssoDirectoryActions = [
  "AddMemberToGroup",
  "CompleteVirtualMfaDeviceRegistration",
  "CompleteWebAuthnDeviceRegistration",
  "CreateAlias",
  "CreateBearerToken",
  "CreateExternalIdPConfigurationForDirectory",
  "CreateGroup",
  "CreateProvisioningTenant",
  "CreateUser",
  "DeleteBearerToken",
  "DeleteExternalIdPCertificate",
  "DeleteExternalIdPConfigurationForDirectory",
  "DeleteGroup",
  "DeleteMfaDeviceForUser",
  "DeleteProvisioningTenant",
  "DeleteUser",
  "DescribeDirectory",
  "DescribeGroup",
  "DescribeGroups",
  "DescribeProvisioningTenant",
  "DescribeUser",
  "DescribeUserByUniqueAttribute",
  "DescribeUsers",
  "DisableExternalIdPConfigurationForDirectory",
  "DisableUser",
  "EnableExternalIdPConfigurationForDirectory",
  "EnableUser",
  "GetAWSSPConfigurationForDirectory",
  "GetGroupId",
  "GetUserId",
  "GetUserPoolInfo",
  "ImportExternalIdPCertificate",
  "IsMemberInGroup",
  "IsMemberInGroups",
  "ListBearerTokens",
  "ListExternalIdPCertificates",
  "ListExternalIdPConfigurationsForDirectory",
  "ListGroups",
  "ListGroupsForMember",
  "ListGroupsForUser",
  "ListMembersInGroup",
  "ListMfaDevicesForUser",
  "ListProvisioningTenants",
  "ListUsers",
  "RemoveMemberFromGroup",
  "SearchGroups",
  "SearchUsers",
  "StartVirtualMfaDeviceRegistration",
  "StartWebAuthnDeviceRegistration",
  "UpdateExternalIdPConfigurationForDirectory",
  "UpdateGroup",
  "UpdateGroupDisplayName",
  "UpdateMfaDeviceForUser",
  "UpdatePassword",
  "UpdateUser",
  "UpdateUserName",
  "VerifyEmail",
] as const;

export type SsoDirectoryAction = (typeof ssoDirectoryActions)[number];

export function ssoDirectory(action: SsoDirectoryAction | "*"): `sso-directory:${SsoDirectoryAction | "*"}` {
  return `sso-directory:${action}` as `sso-directory:${SsoDirectoryAction | "*"}`;
}
