export const supportActions = [
  "AddAttachmentsToSet",
  "AddCommunicationToCase",
  "AddRelatedItemToCase",
  "CreateCase",
  "DescribeAttachment",
  "DescribeCaseAttributes",
  "DescribeCaseOptions",
  "DescribeCases",
  "DescribeCommunication",
  "DescribeCommunications",
  "DescribeCreateCaseOptions",
  "DescribeIssueTypes",
  "DescribeRelatedItems",
  "DescribeServices",
  "DescribeSeverityLevels",
  "DescribeSupportedLanguages",
  "DescribeSupportLevel",
  "DescribeTrustedAdvisorCheckRefreshStatuses",
  "DescribeTrustedAdvisorCheckResult",
  "DescribeTrustedAdvisorChecks",
  "DescribeTrustedAdvisorCheckSummaries",
  "DisconnectLiveContactForCase",
  "DownloadAttachment",
  "GetInteraction",
  "InitiateCallForCase",
  "InitiateChatForCase",
  "InitiateLiveContactForCase",
  "ListInteractionEntries",
  "ListInteractions",
  "PutCaseAttributes",
  "RateCaseCommunication",
  "RefreshTrustedAdvisorCheck",
  "ResolveCase",
  "ResolveInteraction",
  "SearchForCases",
  "StartInteraction",
  "UpdateCaseSeverity",
  "UpdateInteraction",
  "UploadAttachment",
] as const;

export type SupportAction = (typeof supportActions)[number];

export function support(action: SupportAction | "*"): `support:${SupportAction | "*"}` {
  return `support:${action}` as `support:${SupportAction | "*"}`;
}
