export const swfActions = [
  "CancelTimer",
  "CancelWorkflowExecution",
  "CompleteWorkflowExecution",
  "ContinueAsNewWorkflowExecution",
  "CountClosedWorkflowExecutions",
  "CountOpenWorkflowExecutions",
  "CountPendingActivityTasks",
  "CountPendingDecisionTasks",
  "DeleteActivityType",
  "DeleteWorkflowType",
  "DeprecateActivityType",
  "DeprecateDomain",
  "DeprecateWorkflowType",
  "DescribeActivityType",
  "DescribeDomain",
  "DescribeWorkflowExecution",
  "DescribeWorkflowType",
  "FailWorkflowExecution",
  "GetWorkflowExecutionHistory",
  "ListActivityTypes",
  "ListClosedWorkflowExecutions",
  "ListDomains",
  "ListOpenWorkflowExecutions",
  "ListTagsForResource",
  "ListWorkflowTypes",
  "PollForActivityTask",
  "PollForDecisionTask",
  "RecordActivityTaskHeartbeat",
  "RecordMarker",
  "RegisterActivityType",
  "RegisterDomain",
  "RegisterWorkflowType",
  "RequestCancelActivityTask",
  "RequestCancelExternalWorkflowExecution",
  "RequestCancelWorkflowExecution",
  "RespondActivityTaskCanceled",
  "RespondActivityTaskCompleted",
  "RespondActivityTaskFailed",
  "RespondDecisionTaskCompleted",
  "ScheduleActivityTask",
  "SignalExternalWorkflowExecution",
  "SignalWorkflowExecution",
  "StartChildWorkflowExecution",
  "StartTimer",
  "StartWorkflowExecution",
  "TagResource",
  "TerminateWorkflowExecution",
  "UndeprecateActivityType",
  "UndeprecateDomain",
  "UndeprecateWorkflowType",
  "UntagResource",
] as const;

export type SwfAction = (typeof swfActions)[number];

export function swf(action: SwfAction | "*"): `swf:${SwfAction | "*"}` {
  return `swf:${action}` as `swf:${SwfAction | "*"}`;
}
