export const transformCustomActions = [
  "BatchCreateFindings",
  "BatchUpdateFindings",
  "CompleteTransformationPackageUpload",
  "ConverseStream",
  "CreateAnalysis",
  "CreateCampaign",
  "CreateRemediation",
  "CreateRepository",
  "CreateSource",
  "CreateTransformationPackageUrl",
  "DeleteAnalysis",
  "DeleteCampaign",
  "DeleteFinding",
  "DeleteKnowledgeItem",
  "DeleteRemediation",
  "DeleteRepository",
  "DeleteSource",
  "DeleteTransformationPackage",
  "ExecuteTransformation",
  "GetAnalysis",
  "GetCampaign",
  "GetFinding",
  "GetFindingGroups",
  "GetKnowledgeItem",
  "GetRemediation",
  "GetRepository",
  "GetSource",
  "GetTransformationPackageUrl",
  "ListAnalyses",
  "ListCampaignRepositories",
  "ListCampaigns",
  "ListFindings",
  "ListKnowledgeItems",
  "ListRemediations",
  "ListRepositories",
  "ListSources",
  "ListTagsForResource",
  "ListTransformationPackageMetadata",
  "ListTransformationPackageShares",
  "ShareTransformationPackage",
  "TagResource",
  "UnshareTransformationPackage",
  "UntagResource",
  "UpdateAnalysis",
  "UpdateCampaign",
  "UpdateCampaignRepositoryStatus",
  "UpdateKnowledgeItemConfiguration",
  "UpdateKnowledgeItemStatus",
  "UpdateRemediation",
  "UpdateRepository",
  "UpdateSource",
] as const;

export type TransformCustomAction = (typeof transformCustomActions)[number];

export function transformCustom(action: TransformCustomAction | "*"): `transform-custom:${TransformCustomAction | "*"}` {
  return `transform-custom:${action}` as `transform-custom:${TransformCustomAction | "*"}`;
}
