export const transcribeActions = [
  "CreateCallAnalyticsCategory",
  "CreateLanguageModel",
  "CreateMedicalVocabulary",
  "CreateVocabulary",
  "CreateVocabularyFilter",
  "DeleteCallAnalyticsCategory",
  "DeleteCallAnalyticsJob",
  "DeleteLanguageModel",
  "DeleteMedicalScribeJob",
  "DeleteMedicalTranscriptionJob",
  "DeleteMedicalVocabulary",
  "DeleteTranscriptionJob",
  "DeleteVocabulary",
  "DeleteVocabularyFilter",
  "DescribeLanguageModel",
  "GetCallAnalyticsCategory",
  "GetCallAnalyticsJob",
  "GetMedicalScribeJob",
  "GetMedicalScribeStream",
  "GetMedicalTranscriptionJob",
  "GetMedicalVocabulary",
  "GetTranscriptionJob",
  "GetVocabulary",
  "GetVocabularyFilter",
  "ListCallAnalyticsCategories",
  "ListCallAnalyticsJobs",
  "ListLanguageModels",
  "ListMedicalScribeJobs",
  "ListMedicalTranscriptionJobs",
  "ListMedicalVocabularies",
  "ListTagsForResource",
  "ListTranscriptionJobs",
  "ListVocabularies",
  "ListVocabularyFilters",
  "StartCallAnalyticsJob",
  "StartCallAnalyticsStreamTranscription",
  "StartCallAnalyticsStreamTranscriptionWebSocket",
  "StartMedicalScribeJob",
  "StartMedicalScribeStream",
  "StartMedicalStreamTranscription",
  "StartMedicalStreamTranscriptionWebSocket",
  "StartMedicalTranscriptionJob",
  "StartStreamTranscription",
  "StartStreamTranscriptionWebSocket",
  "StartTranscriptionJob",
  "TagResource",
  "UntagResource",
  "UpdateCallAnalyticsCategory",
  "UpdateMedicalVocabulary",
  "UpdateVocabulary",
  "UpdateVocabularyFilter",
] as const;

export type TranscribeAction = (typeof transcribeActions)[number];

export function transcribe(action: TranscribeAction | "*"): `transcribe:${TranscribeAction | "*"}` {
  return `transcribe:${action}` as `transcribe:${TranscribeAction | "*"}`;
}
