export const trustedadvisorActions = [
  "BatchUpdateRecommendationResourceExclusion",
  "DeleteNotificationConfigurationForDelegatedAdmin",
  "DescribeAccount",
  "DescribeAccountAccess",
  "DescribeCheckItems",
  "DescribeCheckRefreshStatuses",
  "DescribeChecks",
  "DescribeCheckStatusHistoryChanges",
  "DescribeCheckSummaries",
  "DescribeNotificationConfigurations",
  "DescribeNotificationPreferences",
  "DescribeOrganization",
  "DescribeOrganizationAccounts",
  "DescribeReports",
  "DescribeRisk",
  "DescribeRiskResources",
  "DescribeRisks",
  "DescribeServiceMetadata",
  "DownloadRisk",
  "ExcludeCheckItems",
  "GenerateReport",
  "GetOrganizationRecommendation",
  "GetRecommendation",
  "IncludeCheckItems",
  "ListAccountsForParent",
  "ListChecks",
  "ListOrganizationalUnitsForParent",
  "ListOrganizationRecommendationAccounts",
  "ListOrganizationRecommendationResources",
  "ListOrganizationRecommendations",
  "ListRecommendationResources",
  "ListRecommendations",
  "ListRecommendationsForResource",
  "ListRoots",
  "RefreshCheck",
  "SetAccountAccess",
  "SetOrganizationAccess",
  "UpdateNotificationConfigurations",
  "UpdateNotificationPreferences",
  "UpdateOrganizationRecommendationLifecycle",
  "UpdateRecommendationLifecycle",
  "UpdateRiskStatus",
] as const;

export type TrustedadvisorAction = (typeof trustedadvisorActions)[number];

export function trustedadvisor(action: TrustedadvisorAction | "*"): `trustedadvisor:${TrustedadvisorAction | "*"}` {
  return `trustedadvisor:${action}` as `trustedadvisor:${TrustedadvisorAction | "*"}`;
}
