export const wafv2Actions = [
  "AssociateWebACL",
  "CheckCapacity",
  "CreateAPIKey",
  "CreateIPSet",
  "CreateRegexPatternSet",
  "CreateRuleGroup",
  "CreateWebACL",
  "DeleteAPIKey",
  "DeleteFirewallManagerRuleGroups",
  "DeleteIPSet",
  "DeleteLoggingConfiguration",
  "DeletePermissionPolicy",
  "DeleteRegexPatternSet",
  "DeleteRuleGroup",
  "DeleteWebACL",
  "DescribeAllManagedProducts",
  "DescribeManagedProductsByVendor",
  "DescribeManagedRuleGroup",
  "DisassociateFirewallManager",
  "DisassociateWebACL",
  "GenerateMobileSdkReleaseUrl",
  "GetDecryptedAPIKey",
  "GetIPSet",
  "GetLoggingConfiguration",
  "GetManagedRuleSet",
  "GetMobileSdkRelease",
  "GetPermissionPolicy",
  "GetRateBasedStatementManagedKeys",
  "GetRegexPatternSet",
  "GetRuleGroup",
  "GetSampledRequests",
  "GetTopPathStatisticsByTraffic",
  "GetWebACL",
  "GetWebACLForResource",
  "ListAPIKeys",
  "ListAvailableManagedRuleGroups",
  "ListAvailableManagedRuleGroupVersions",
  "ListIPSets",
  "ListLoggingConfigurations",
  "ListManagedRuleSets",
  "ListMobileSdkReleases",
  "ListRegexPatternSets",
  "ListResourcesForWebACL",
  "ListRuleGroups",
  "ListTagsForResource",
  "ListWebACLs",
  "PutFirewallManagerRuleGroups",
  "PutLoggingConfiguration",
  "PutManagedRuleSetVersions",
  "PutPermissionPolicy",
  "TagResource",
  "UntagResource",
  "UpdateIPSet",
  "UpdateManagedRuleSetVersionExpiryDate",
  "UpdateRegexPatternSet",
  "UpdateRuleGroup",
  "UpdateWebACL",
] as const;

export type Wafv2Action = (typeof wafv2Actions)[number];

export function wafv2(action: Wafv2Action | "*"): `wafv2:${Wafv2Action | "*"}` {
  return `wafv2:${action}` as `wafv2:${Wafv2Action | "*"}`;
}
