export const wickrActions = [
  "BatchCreateUser",
  "BatchDeleteUser",
  "BatchLookupUserUname",
  "BatchReinviteUser",
  "BatchResetDevicesForUser",
  "BatchToggleUserSuspendStatus",
  "CreateAdminSession",
  "CreateBot",
  "CreateDataRetentionBot",
  "CreateDataRetentionBotChallenge",
  "CreateNetwork",
  "CreateSecurityGroup",
  "DeleteBot",
  "DeleteDataRetentionBot",
  "DeleteNetwork",
  "DeleteSecurityGroup",
  "GetBot",
  "GetBotsCount",
  "GetDataRetentionBot",
  "GetGuestUserHistoryCount",
  "GetNetwork",
  "GetNetworkSettings",
  "GetOidcInfo",
  "GetOpentdfConfig",
  "GetSecurityGroup",
  "GetUser",
  "GetUsersCount",
  "ListBlockedGuestUsers",
  "ListBots",
  "ListDevicesForUser",
  "ListGuestUsers",
  "ListNetworks",
  "ListSecurityGroups",
  "ListSecurityGroupUsers",
  "ListTagsForResource",
  "ListUsers",
  "RegisterOidcConfig",
  "RegisterOidcConfigTest",
  "RegisterOpentdfConfig",
  "TagResource",
  "UntagResource",
  "UpdateBot",
  "UpdateDataRetention",
  "UpdateGuestUser",
  "UpdateNetworkDetails",
  "UpdateNetworkSettings",
  "UpdateSecurityGroup",
  "UpdateUser",
] as const;

export type WickrAction = (typeof wickrActions)[number];

export function wickr(action: WickrAction | "*"): `wickr:${WickrAction | "*"}` {
  return `wickr:${action}` as `wickr:${WickrAction | "*"}`;
}
