export const workdocsActions = [
  "AbortDocumentVersionUpload",
  "ActivateUser",
  "AddNotificationPermissions",
  "AddResourcePermissions",
  "AddUserToGroup",
  "CheckAlias",
  "CreateComment",
  "CreateCustomMetadata",
  "CreateFolder",
  "CreateInstance",
  "CreateLabels",
  "CreateNotificationSubscription",
  "CreateUser",
  "DeactivateUser",
  "DeleteComment",
  "DeleteCustomMetadata",
  "DeleteDocument",
  "DeleteDocumentVersion",
  "DeleteFolder",
  "DeleteFolderContents",
  "DeleteInstance",
  "DeleteLabels",
  "DeleteNotificationPermissions",
  "DeleteNotificationSubscription",
  "DeleteUser",
  "DeregisterDirectory",
  "DescribeActivities",
  "DescribeAvailableDirectories",
  "DescribeComments",
  "DescribeDocumentVersions",
  "DescribeFolderContents",
  "DescribeGroups",
  "DescribeInstanceExports",
  "DescribeInstances",
  "DescribeNotificationPermissions",
  "DescribeNotificationSubscriptions",
  "DescribeResourcePermissions",
  "DescribeRootFolders",
  "DescribeUsers",
  "DownloadDocumentVersion",
  "GetCurrentUser",
  "GetDocument",
  "GetDocumentPath",
  "GetDocumentVersion",
  "GetFolder",
  "GetFolderPath",
  "GetGroup",
  "GetResources",
  "InitiateDocumentVersionUpload",
  "RegisterDirectory",
  "RemoveAllResourcePermissions",
  "RemoveResourcePermission",
  "RestoreDocumentVersions",
  "SearchResources",
  "StartInstanceExport",
  "UpdateDocument",
  "UpdateDocumentVersion",
  "UpdateFolder",
  "UpdateInstanceAlias",
  "UpdateUser",
  "UpdateUserAdministrativeSettings",
] as const;

export type WorkdocsAction = (typeof workdocsActions)[number];

export function workdocs(action: WorkdocsAction | "*"): `workdocs:${WorkdocsAction | "*"}` {
  return `workdocs:${action}` as `workdocs:${WorkdocsAction | "*"}`;
}
