export const xrayActions = [
  "BatchGetTraces",
  "BatchGetTraceSummaryById",
  "CancelTraceRetrieval",
  "CreateGroup",
  "CreateSamplingRule",
  "DeleteGroup",
  "DeleteResourcePolicy",
  "DeleteSamplingRule",
  "GetDistinctTraceGraphs",
  "GetEncryptionConfig",
  "GetGroup",
  "GetGroups",
  "GetIndexingRules",
  "GetInsight",
  "GetInsightEvents",
  "GetInsightImpactGraph",
  "GetInsightSummaries",
  "GetRetrievedTracesGraph",
  "GetSamplingRules",
  "GetSamplingStatisticSummaries",
  "GetSamplingTargets",
  "GetServiceGraph",
  "GetTimeSeriesServiceStatistics",
  "GetTraceGraph",
  "GetTraceSegmentDestination",
  "GetTraceSummaries",
  "Link",
  "ListResourcePolicies",
  "ListRetrievedTraces",
  "ListTagsForResource",
  "PutEncryptionConfig",
  "PutResourcePolicy",
  "PutSpans",
  "PutSpansForIndexing",
  "PutTelemetryRecords",
  "PutTraceSegments",
  "StartTraceRetrieval",
  "TagResource",
  "UntagResource",
  "UpdateGroup",
  "UpdateIndexingRule",
  "UpdateSamplingRule",
  "UpdateTraceSegmentDestination",
] as const;

export type XrayAction = (typeof xrayActions)[number];

export function xray(action: XrayAction | "*"): `xray:${XrayAction | "*"}` {
  return `xray:${action}` as `xray:${XrayAction | "*"}`;
}
