import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const sourceUrl = "https://awspolicygen.s3.amazonaws.com/js/policies.js";
const outputPath = resolve("src/catalog.ts");
const fetchTimeoutMs = 30_000;

async function main() {
  const rawSource = await fetchPoliciesJs();
  const normalizedCatalog = normalizeCatalog({
    rawSource,
    sourceUrl,
  });
  const nextContent = renderCatalogModule({
    catalog: normalizedCatalog,
  });
  const currentContent = await readIfExists(outputPath);

  if (currentContent === nextContent) {
    console.log(
      `IAM action catalog is up to date (${Object.keys(normalizedCatalog.services).length} services, ${normalizedCatalog.actionCount} actions).`,
    );
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, nextContent, "utf8");

  console.log(
    `Updated ${outputPath} (${Object.keys(normalizedCatalog.services).length} services, ${normalizedCatalog.actionCount} actions).`,
  );
}

async function fetchPoliciesJs() {
  const abortController = new AbortController();
  const timeout = setTimeout(() => abortController.abort(), fetchTimeoutMs);

  try {
    const response = await fetch(sourceUrl, {
      signal: abortController.signal,
      headers: {
        accept:
          "application/javascript, text/javascript, text/plain;q=0.9, */*;q=0.8",
      },
    });
    if (!response.ok) {
      throw new Error(
        `Failed to download IAM action catalog from ${sourceUrl}: ${response.status} ${response.statusText}`,
      );
    }
    return await response.text();
  } finally {
    clearTimeout(timeout);
  }
}

function parseRawServiceMap(rawSource, sourceUrl) {
  const matched = rawSource.match(
    /app\.PolicyEditorConfig\s*=\s*(\{[\s\S]*\})\s*$/,
  );
  if (matched?.[1] == null) {
    throw new Error(
      `Could not locate app.PolicyEditorConfig in ${sourceUrl}.`,
    );
  }

  const parsed = JSON.parse(matched[1]);
  const rawServiceMap = parsed?.serviceMap;
  if (rawServiceMap == null || typeof rawServiceMap !== "object") {
    throw new Error(
      `Unexpected serviceMap payload in ${sourceUrl}.`,
    );
  }

  return rawServiceMap;
}

function normalizeCatalog(props) {
  const rawServiceMap = parseRawServiceMap(props.rawSource, props.sourceUrl);

  const serviceEntries = Object.values(rawServiceMap)
    .map(normalizeService)
    .filter((s) => s != null)
    .sort((a, b) => a.prefix.localeCompare(b.prefix));

  const services = Object.fromEntries(
    serviceEntries.map((s) => [s.prefix, s.actions]),
  );

  return {
    sourceUrl: props.sourceUrl,
    sourceSha256: sha256(props.rawSource),
    actionCount: serviceEntries.reduce((t, s) => t + s.actions.length, 0),
    services,
  };
}

function extractServicePrefix(service) {
  if (service == null || typeof service !== "object") return null;
  if (!("StringPrefix" in service)) return null;
  const prefix = String(service.StringPrefix ?? "").trim();
  return prefix.length > 0 ? prefix : null;
}

function extractUniqueActions(service) {
  if (!("Actions" in service) || !Array.isArray(service.Actions)) return [];
  return [...new Set(service.Actions.map((a) => String(a).trim()))]
    .filter((a) => a.length > 0)
    .sort((a, b) => a.localeCompare(b));
}

function normalizeService(service) {
  const prefix = extractServicePrefix(service);
  if (prefix == null) return null;

  const actions = extractUniqueActions(service);
  if (actions.length === 0) return null;

  return { prefix, actions };
}

function renderCatalogModule(props) {
  const serializedServices = JSON.stringify(props.catalog.services, null, 2);
  const servicePrefixes = Object.keys(props.catalog.services);
  const iamHelperEntries = servicePrefixes
    .map((prefix) => {
      const key = isIdentifierSafe(prefix) ? prefix : JSON.stringify(prefix);
      return `  ${key}: (action) => \`${prefix}:\${action}\`,`;
    })
    .join("\n");

  return `/**
 * Generated by "npm run generate".
 * Source: ${props.catalog.sourceUrl}
 * Source SHA256: ${props.catalog.sourceSha256}
 *
 * Do not edit by hand.
 */
export const iamActionCatalog = ${serializedServices} as const;

export const iamActionCatalogSourceUrl = ${JSON.stringify(props.catalog.sourceUrl)};
export const iamActionCatalogSourceSha256 = ${JSON.stringify(props.catalog.sourceSha256)};
export const iamActionCatalogActionCount = ${props.catalog.actionCount};

import type { IamHelperObject } from "./helpers.js";

/**
 * Per-service IAM action helpers for inline policies.
 *
 * @example
 * iam.s3("GetObject")                          // "s3:GetObject"
 * iam.identitystore("CreateGroupMembership")   // "identitystore:CreateGroupMembership"
 * iam["sso-directory"]("SearchUsers")          // "sso-directory:SearchUsers"
 */
export const iam: IamHelperObject = {
${iamHelperEntries}
} as IamHelperObject;
`;
}

function isIdentifierSafe(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value);
}

async function readIfExists(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNotFoundError(error)) {
      return null;
    }
    throw error;
  }
}

function isNotFoundError(error) {
  return (
    error != null &&
    typeof error === "object" &&
    "code" in error &&
    error.code === "ENOENT"
  );
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

await main();
