import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const sourceUrl = "https://awspolicygen.s3.amazonaws.com/js/policies.js";
const outputPath = resolve("src/catalog.ts");
const fetchTimeoutMs = 30_000;

async function main() {
  const rawSource = await fetchPoliciesJs();
  const normalizedCatalog = normalizeCatalog({
    rawSource,
    sourceUrl,
  });
  const nextContent = renderCatalogModule({
    catalog: normalizedCatalog,
  });
  const currentContent = await readIfExists(outputPath);

  if (currentContent === nextContent) {
    console.log(
      `IAM action catalog is up to date (${Object.keys(normalizedCatalog.services).length} services, ${normalizedCatalog.actionCount} actions).`,
    );
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, nextContent, "utf8");

  console.log(
    `Updated ${outputPath} (${Object.keys(normalizedCatalog.services).length} services, ${normalizedCatalog.actionCount} actions).`,
  );
}

async function fetchPoliciesJs() {
  const abortController = new AbortController();
  const timeout = setTimeout(() => abortController.abort(), fetchTimeoutMs);

  try {
    const response = await fetch(sourceUrl, {
      signal: abortController.signal,
      headers: {
        accept:
          "application/javascript, text/javascript, text/plain;q=0.9, */*;q=0.8",
      },
    });
    if (!response.ok) {
      throw new Error(
        `Failed to download IAM action catalog from ${sourceUrl}: ${response.status} ${response.statusText}`,
      );
    }
    return await response.text();
  } finally {
    clearTimeout(timeout);
  }
}

function normalizeCatalog(props) {
  const matched = props.rawSource.match(
    /app\.PolicyEditorConfig\s*=\s*(\{[\s\S]*\})\s*$/,
  );
  if (matched?.[1] == null) {
    throw new Error(
      `Could not locate app.PolicyEditorConfig in ${props.sourceUrl}.`,
    );
  }

  const parsed = JSON.parse(matched[1]);
  const rawServiceMap = parsed?.serviceMap;
  if (rawServiceMap == null || typeof rawServiceMap !== "object") {
    throw new Error(
      `Unexpected serviceMap payload in ${props.sourceUrl}.`,
    );
  }

  const serviceEntries = Object.values(rawServiceMap)
    .map((service) => normalizeService(service))
    .filter((service) => service != null)
    .sort((left, right) => left.prefix.localeCompare(right.prefix));

  const services = Object.fromEntries(
    serviceEntries.map((service) => [service.prefix, service.actions]),
  );

  return {
    sourceUrl: props.sourceUrl,
    sourceSha256: sha256(props.rawSource),
    actionCount: serviceEntries.reduce(
      (total, service) => total + service.actions.length,
      0,
    ),
    services,
  };
}

function normalizeService(service) {
  if (service == null || typeof service !== "object") {
    return null;
  }

  const prefix =
    "StringPrefix" in service
      ? String(service.StringPrefix ?? "").trim()
      : "";
  const rawActions =
    "Actions" in service && Array.isArray(service.Actions)
      ? service.Actions
      : [];

  if (prefix.length === 0 || rawActions.length === 0) {
    return null;
  }

  const actions = [
    ...new Set(rawActions.map((action) => String(action).trim())),
  ]
    .filter((action) => action.length > 0)
    .sort((left, right) => left.localeCompare(right));

  if (actions.length === 0) {
    return null;
  }

  return {
    prefix,
    actions,
  };
}

function renderCatalogModule(props) {
  const serializedServices = JSON.stringify(props.catalog.services, null, 2);
  const servicePrefixes = Object.keys(props.catalog.services);
  const iamHelperEntries = servicePrefixes
    .map((prefix) => {
      const key = isIdentifierSafe(prefix) ? prefix : JSON.stringify(prefix);
      return `  ${key}: (action) => \`${prefix}:\${action}\`,`;
    })
    .join("\n");

  return `/**
 * Generated by "npm run generate".
 * Source: ${props.catalog.sourceUrl}
 * Source SHA256: ${props.catalog.sourceSha256}
 *
 * Do not edit by hand.
 */
export const iamActionCatalog = ${serializedServices} as const;

export const iamActionCatalogSourceUrl = ${JSON.stringify(props.catalog.sourceUrl)};
export const iamActionCatalogSourceSha256 = ${JSON.stringify(props.catalog.sourceSha256)};
export const iamActionCatalogActionCount = ${props.catalog.actionCount};

import type { IamHelperObject } from "./helpers.js";

/**
 * Per-service IAM action helpers for inline policies.
 *
 * @example
 * iam.s3("GetObject")                          // "s3:GetObject"
 * iam.identitystore("CreateGroupMembership")   // "identitystore:CreateGroupMembership"
 * iam["sso-directory"]("SearchUsers")          // "sso-directory:SearchUsers"
 */
export const iam: IamHelperObject = {
${iamHelperEntries}
} as IamHelperObject;
`;
}

function isIdentifierSafe(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value);
}

async function readIfExists(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNotFoundError(error)) {
      return null;
    }
    throw error;
  }
}

function isNotFoundError(error) {
  return (
    error != null &&
    typeof error === "object" &&
    "code" in error &&
    error.code === "ENOENT"
  );
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

await main();
