type NormalizedCatalog = {
  sourceUrl: string;
  sourceSha256: string;
  actionCount: number;
  services: Record<string, string[]>;
};

/**
 * Renders the `_meta.ts` file content from a normalized catalog.
 * The generated file exports `iamActionCatalog`, `iamActionCatalogSourceUrl`,
 * `iamActionCatalogSourceSha256`, and `iamActionCatalogActionCount`.
 */
export function renderMetaFile(catalog: NormalizedCatalog): string {
  const serializedServices = JSON.stringify(catalog.services, null, 2);

  return `/**
 * Generated by "npm run generate".
 * Source: ${catalog.sourceUrl}
 * Source SHA256: ${catalog.sourceSha256}
 *
 * Do not edit by hand.
 */
export const iamActionCatalog = ${serializedServices} as const;

export const iamActionCatalogSourceUrl = ${JSON.stringify(catalog.sourceUrl)};
export const iamActionCatalogSourceSha256 = ${JSON.stringify(catalog.sourceSha256)};
export const iamActionCatalogActionCount = ${catalog.actionCount};
`;
}
